<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Worklist</name>
   <tag></tag>
   <elementGuidId>1e628a90-8c1c-43d2-b151-634026370047</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='My Task'])[1]/following::a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>de737aba-f8f6-4f90-9bea-7ade830fa65d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-head</value>
      <webElementGuid>9fd6b8ff-8384-4b24-8db1-108cdc70cb19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/worklist</value>
      <webElementGuid>d3366fb0-7006-4157-ab5a-dc9caf1e7fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Worklist </value>
      <webElementGuid>56f5869e-4861-4736-9099-4031bc1b3921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-admin-layout[1]/div[@class=&quot;bootstrap-wrapper cus-fixed&quot;]/div[@class=&quot;left-menu&quot;]/app-left-menu[1]/div[@class=&quot;pitstops-left-menu cus-scrollbar&quot;]/div[@class=&quot;item-menu&quot;]/a[@class=&quot;item-head&quot;]</value>
      <webElementGuid>4f82a461-a9a6-4417-981c-4d1e43747bb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Task'])[1]/following::a[1]</value>
      <webElementGuid>d36e8c34-3873-4dc9-a23c-5e3ac3fd14f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Performance'])[1]/following::a[2]</value>
      <webElementGuid>a41d302a-a091-44d9-a98d-dd8641de0e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workshop'])[1]/preceding::a[1]</value>
      <webElementGuid>8d57c0c2-5eb0-4626-9db7-1e025d0178e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/worklist')]</value>
      <webElementGuid>90cc6556-03ff-475c-bfa2-2084c36c4f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>58d5f465-8c36-49b7-ab03-527a93e4cc98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/worklist' and (text() = ' Worklist ' or . = ' Worklist ')]</value>
      <webElementGuid>c02099f9-6078-455a-b260-8fd2c23c5dfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
