<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Approval</name>
   <tag></tag>
   <elementGuidId>3075195a-544c-49d5-b8bd-8dd61106ec7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-request-screening//div[4]//kendo-expansionpanel/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>kendo-expansionpanel.cs-expansionpanel.k-expander.k-state-focus > div.k-expander-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>238a04cd-2ba3-4219-8cac-b68e21e29594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-expander-header</value>
      <webElementGuid>8638a01b-c2aa-49b6-b7fd-ffb53f621a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approval</value>
      <webElementGuid>ea827499-8e85-4b24-b857-fa6c24086f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-tns-0-1&quot;]/app-root[1]/app-admin-layout[1]/div[@class=&quot;bootstrap-wrapper cus-fixed&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/app-request-screening[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;bootstrap-wrapper&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;row kd-custom&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;wrapper planing-wrapper ng-star-inserted&quot;]/kendo-expansionpanel[@class=&quot;cs-expansionpanel k-expander k-state-focus&quot;]/div[@class=&quot;k-expander-header&quot;]</value>
      <webElementGuid>51b97a3d-046d-4bfd-b1d2-f91ee33d5feb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reviewed'])[2]/following::div[2]</value>
      <webElementGuid>a9a71ae0-5e84-4741-9f18-4ff5cbe6e078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='at'])[1]/following::div[3]</value>
      <webElementGuid>ae1b1e57-c896-4edf-b670-b3a458b3d174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/kendo-expansionpanel/div</value>
      <webElementGuid>6d76a61e-6fee-41f8-b8e4-4ad41a5ae2b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Approval' or . = 'Approval')]</value>
      <webElementGuid>e659bcc9-f1f1-4b6f-8b5e-9ba74739070d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
