<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PC Ammonia Sdn Bhd  PETRONAS Penapis_a29677</name>
   <tag></tag>
   <elementGuidId>945c2266-76cb-4887-a573-bc3dfbd45910</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='opu-list']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#opu-list</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>538fde43-ae34-45b2-a451-27ca1a558a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>opu-list</value>
      <webElementGuid>7524fbe1-bcb3-493f-b328-6eea9c82c438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> PC Ammonia Sdn Bhd  PETRONAS Penapisan Terengganu Sdn Bhd  Demo  PETRONAS Carigali Sarawak Asset  Malaysia LNG Sdn Bhd  PCGB PCMSB Plant 1 </value>
      <webElementGuid>f2eeaf8a-62fa-4931-89f5-663d4f9c9958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opu-list&quot;)</value>
      <webElementGuid>f859aad4-25fe-41b1-814b-f05afac17e3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='opu-list']</value>
      <webElementGuid>e5e1cdc1-b7f5-4ca0-86ad-84ff2d898247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPU'])[1]/following::select[1]</value>
      <webElementGuid>4625eab5-24e8-4d38-8090-11b4180fd2a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/preceding::select[1]</value>
      <webElementGuid>84547327-bfd1-4f83-a32d-2e665a7bcc37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Planning Homepage'])[1]/preceding::select[2]</value>
      <webElementGuid>7e3208bb-a5a5-4055-888e-28e74d32fca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>7fd58248-ab83-4617-af89-fdda15a57997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'opu-list' and (text() = ' PC Ammonia Sdn Bhd  PETRONAS Penapisan Terengganu Sdn Bhd  Demo  PETRONAS Carigali Sarawak Asset  Malaysia LNG Sdn Bhd  PCGB PCMSB Plant 1 ' or . = ' PC Ammonia Sdn Bhd  PETRONAS Penapisan Terengganu Sdn Bhd  Demo  PETRONAS Carigali Sarawak Asset  Malaysia LNG Sdn Bhd  PCGB PCMSB Plant 1 ')]</value>
      <webElementGuid>e9d74d3a-03bd-44d4-b722-22f27205908f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
