<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Demo - Training  MNLG - Demo TP  Dem_be5ca4</name>
   <tag></tag>
   <elementGuidId>0f11ad07-992f-4e8a-82f4-e183b26326a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='event-list']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#event-list</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>52a2fbfc-3a21-45c2-a93b-7f7c88351a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>event-list</value>
      <webElementGuid>ad336436-0115-410f-a711-420f763fd1a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Demo - Training  MNLG - Demo TP  Demo-Nayli  DEMO_SN  MRCSB-TP-2025  EVENT - REGRESSION  EVENT - REGRESSION 2  REGRESSION - LOC  TCBODS-01 </value>
      <webElementGuid>4804b6de-2240-42f1-b136-47cfeaad1be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;event-list&quot;)</value>
      <webElementGuid>aeae61da-8c87-4558-aec9-12038c4b168b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='event-list']</value>
      <webElementGuid>80a02414-dab5-4fa9-ab7b-ff85f9d55905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/following::select[1]</value>
      <webElementGuid>c3d11840-84d0-4611-a49c-094749361d55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPU'])[1]/following::select[2]</value>
      <webElementGuid>9038cb45-02e3-4735-9bc2-8d4e5289e9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Execution Homepage'])[1]/preceding::select[1]</value>
      <webElementGuid>146bc8b2-a158-4f98-a2c5-9465e1c1930a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Notifications (0)'])[1]/preceding::select[1]</value>
      <webElementGuid>95f307d3-4adb-401f-ac33-5933e38256da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/select</value>
      <webElementGuid>58f2af26-dd95-4352-beef-223214cf6ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'event-list' and (text() = ' Demo - Training  MNLG - Demo TP  Demo-Nayli  DEMO_SN  MRCSB-TP-2025  EVENT - REGRESSION  EVENT - REGRESSION 2  REGRESSION - LOC  TCBODS-01 ' or . = ' Demo - Training  MNLG - Demo TP  Demo-Nayli  DEMO_SN  MRCSB-TP-2025  EVENT - REGRESSION  EVENT - REGRESSION 2  REGRESSION - LOC  TCBODS-01 ')]</value>
      <webElementGuid>fd4a493d-7bb3-4d48-ac5e-fc2883f0a073</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
