<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Role Management</name>
   <tag></tag>
   <elementGuidId>0d325228-9709-4028-af6d-3d738585de90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@id, 'sub-5d02109c-56d6-4ef9-8230-08da655b00c5')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sub-5d02109c-56d6-4ef9-8230-08da655b00c5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>19f02afa-409c-438f-a2f7-23dc65c7d086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-menu</value>
      <webElementGuid>38ab5899-2494-4989-8b3f-fd35ae563ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sub-5d02109c-56d6-4ef9-8230-08da655b00c5</value>
      <webElementGuid>93895c9e-5911-4f6e-b29c-70c84b9570ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/entprise/event/role</value>
      <webElementGuid>43295f2e-abec-4252-9d6c-a889d9d51ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Role Management </value>
      <webElementGuid>f09174e5-dcfb-43d0-ba7d-9c1298097a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sub-5d02109c-56d6-4ef9-8230-08da655b00c5&quot;)</value>
      <webElementGuid>9781419a-c4d5-4700-8e6c-8ac287939005</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='sub-5d02109c-56d6-4ef9-8230-08da655b00c5']</value>
      <webElementGuid>80cc77a9-3ac3-43a8-a30d-c3a728ef353c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event Registration'])[2]/following::a[1]</value>
      <webElementGuid>ab7f962c-90c8-4712-812a-5b959cf5d937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event management, role &amp; user management and master data management.'])[1]/following::a[2]</value>
      <webElementGuid>d57b9dd2-839d-448e-b7aa-ad332b15e66a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Management'])[2]/preceding::a[1]</value>
      <webElementGuid>4d627416-7f3f-4e0f-8bc4-1e74c4d61a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/entprise/event/role')])[2]</value>
      <webElementGuid>10439ef4-04f1-46ee-8fee-d5e5569dc6fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/a[2]</value>
      <webElementGuid>14e91394-6385-4501-9c11-f7a3674f9058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'sub-5d02109c-56d6-4ef9-8230-08da655b00c5' and @href = '/entprise/event/role' and (text() = ' Role Management ' or . = ' Role Management ')]</value>
      <webElementGuid>048c9621-886d-409f-ac16-d1773f90315d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
