<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Role Management</name>
   <tag></tag>
   <elementGuidId>0d325228-9709-4028-af6d-3d738585de90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sub-5d02109c-56d6-4ef9-8230-08da655b00c5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sub-5d02109c-56d6-4ef9-8230-08da655b00c5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>244a89e1-94c4-4806-aa41-fbeb08bc22cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-menu</value>
      <webElementGuid>a0b7c943-5ba2-4fcc-aab5-fb1fad8385cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sub-5d02109c-56d6-4ef9-8230-08da655b00c5</value>
      <webElementGuid>0fe0f5ba-5c2a-4975-9d86-a038fdf34f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/entprise/event/role</value>
      <webElementGuid>d230b343-4579-4175-ad6c-30b76323fcea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Role Management </value>
      <webElementGuid>e93d0b6e-4bb9-4d02-8d1a-7c47c680273c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sub-5d02109c-56d6-4ef9-8230-08da655b00c5&quot;)</value>
      <webElementGuid>7656ff7a-6c5c-461e-8e28-fa3e8e60a8c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='sub-5d02109c-56d6-4ef9-8230-08da655b00c5']</value>
      <webElementGuid>9cce7a1d-0517-4ad7-9d0c-88ccfa90e03b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event Registration'])[2]/following::a[1]</value>
      <webElementGuid>af158703-9bbb-481c-a09f-1f438fa8af62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event management, role &amp; user management and master data management.'])[1]/following::a[2]</value>
      <webElementGuid>63b3ccbc-7d2e-46f3-981f-828364174ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Management'])[2]/preceding::a[1]</value>
      <webElementGuid>5a42da02-03e7-43d7-952a-73c9ca9d2847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/entprise/event/role')])[2]</value>
      <webElementGuid>d9f0304b-361c-4068-bb0e-79a9691e8b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/a[2]</value>
      <webElementGuid>ad9feec2-d0d9-4e6a-940c-3a32d812785b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'sub-5d02109c-56d6-4ef9-8230-08da655b00c5' and @href = '/entprise/event/role' and (text() = ' Role Management ' or . = ' Role Management ')]</value>
      <webElementGuid>306d7803-af69-4a2b-94d0-901748fdb36a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
