<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_User Management</name>
   <tag></tag>
   <elementGuidId>00ad4265-9eb5-4e84-a4af-ba13adbe15a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sub-89929f77-3cf0-4223-8231-08da655b00c5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sub-89929f77-3cf0-4223-8231-08da655b00c5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>60cfbef6-67ff-4609-b062-fb305932fb1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-menu</value>
      <webElementGuid>1030978c-89f2-4274-86e9-34c0de49545c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sub-89929f77-3cf0-4223-8231-08da655b00c5</value>
      <webElementGuid>74e1e324-770e-4ef3-8d58-de239dfe8e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/user-management</value>
      <webElementGuid>1c72d668-9ffd-48c8-b977-c14a12a26e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> User Management </value>
      <webElementGuid>7acb72b5-7879-45d2-90cd-67fa6ac0e517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sub-89929f77-3cf0-4223-8231-08da655b00c5&quot;)</value>
      <webElementGuid>f699fb3f-8eca-4c24-85c9-e5e5765c821c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='sub-89929f77-3cf0-4223-8231-08da655b00c5']</value>
      <webElementGuid>9f44174e-b380-401d-b440-ce8778b177ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role Management'])[2]/following::a[1]</value>
      <webElementGuid>7ba88fd3-46d4-4a5c-98fa-fa67bc51f89a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event Registration'])[2]/following::a[2]</value>
      <webElementGuid>e8bcf521-3c8e-4004-8760-e543807af1f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Data'])[4]/preceding::a[1]</value>
      <webElementGuid>7eb2e152-68e0-48cc-9d96-5eb24d6c94c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/user-management')])[4]</value>
      <webElementGuid>3fdfc1bc-0d8d-446d-aa35-9fa8d5b2e9d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/a[3]</value>
      <webElementGuid>487ee0e1-b80e-4526-84cf-d273ce6e8ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'sub-89929f77-3cf0-4223-8231-08da655b00c5' and @href = '/user-management' and (text() = ' User Management ' or . = ' User Management ')]</value>
      <webElementGuid>184ce302-3d7d-422d-915d-d6e6f2ade0ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
