<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm - Edit Role</name>
   <tag></tag>
   <elementGuidId>d60482c5-d01a-4c8f-ba4e-9fcda9ea95fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;inform-modal&quot;]/div[3]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.delete-confirm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ff5c823a-7d79-4e15-ad05-7f80ea4cf746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>delete-confirm</value>
      <webElementGuid>6f6b696a-0738-4ef6-b1b6-feadd254247b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Confirm </value>
      <webElementGuid>16045e18-87a6-4c0d-81e1-feb737f24ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delete&quot;)/div[@class=&quot;jw-modal-footer&quot;]/button[@class=&quot;delete-confirm&quot;]</value>
      <webElementGuid>2432b334-e68b-48dd-8ded-590b8439d640</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='delete']/div[3]/button[2]</value>
      <webElementGuid>6fedbcf2-0ded-4465-a9d3-f2500cf1f304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>2306d31f-7dc2-4124-90f3-89d632e9908b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to delete this user?'])[1]/following::button[2]</value>
      <webElementGuid>a4a05471-9441-42ba-a0e3-41d8aa4d356c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm']/parent::*</value>
      <webElementGuid>57e92fc4-08c2-4150-86f6-2b5db0c125f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button[2]</value>
      <webElementGuid>07726efb-efdb-4095-8e19-e8fc7414d7f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Confirm ' or . = ' Confirm ')]</value>
      <webElementGuid>bfc6ff3f-c86f-43ee-9d8d-9c526a5589e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
