<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add new role</name>
   <tag></tag>
   <elementGuidId>56b214bf-f9df-4b32-b71a-f0cdce37233b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='k-tabstrip-tabpanel-0']/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.add-btn.k-button.k-button-icontext.k-state-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6ce4eaf4-66ca-4ee9-a4a6-de5c041518c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon</name>
      <type>Main</type>
      <value>plus</value>
      <webElementGuid>6c53fc7d-9aa3-4b26-bf09-84cf20032251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add-btn k-button k-button-icontext k-state-focused</value>
      <webElementGuid>7472e754-52a1-463e-b2f4-20cf6918942a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6685966a-2752-496e-bd1d-0e847da010f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e168ebc8-5a69-45e1-afc9-ef81a080ecf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>be1ec402-a6f9-42cd-b89f-c885d027384b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add new role </value>
      <webElementGuid>004e4f87-1a79-45a7-a124-54df78597d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-tabstrip-tabpanel-0&quot;)/div[@class=&quot;role-content ng-star-inserted&quot;]/button[@class=&quot;add-btn k-button k-button-icontext k-state-focused&quot;]</value>
      <webElementGuid>e8458283-e40d-421a-a88b-989a783380bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='k-tabstrip-tabpanel-0']/div[2]/button</value>
      <webElementGuid>754c61ba-6756-45bd-bada-6800e72601bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add new Role by clicking Add new role button'])[1]/following::button[1]</value>
      <webElementGuid>32fa3928-91ac-4a2a-ad70-79fa93250a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Roles, yet.'])[1]/following::button[1]</value>
      <webElementGuid>5cd85fa2-c4f6-4fc8-880b-5ee349b734d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>bd7675d0-212d-46d7-ad9e-c69570e357a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::button[2]</value>
      <webElementGuid>d0afb378-99cc-4730-9c54-e042693a0345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add new role']/parent::*</value>
      <webElementGuid>ab5ab408-64b6-49fd-8167-a4d5ffb8f325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>060486cf-0d29-4e88-809d-4bacdbef3db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Add new role ' or . = ' Add new role ')]</value>
      <webElementGuid>3abd718a-5e91-46b3-8d37-4d2e09146ec0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
