<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Resources</name>
   <tag></tag>
   <elementGuidId>14659734-ee53-40e2-931f-79dbfc33c859</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@role='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.item-1.left-20.k-button.k-primary.ng-star-inserted.k-state-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f7201d5c-c7aa-4522-857b-126bc4a6beaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-1 left-20 k-button k-primary ng-star-inserted k-state-focused</value>
      <webElementGuid>714efd31-c747-4b74-8cf7-f69b9fbc2a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>00bb1c6f-523c-451d-adfc-9abdac34a111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5b6757de-c857-4a85-aceb-1fc0886774e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>d4c8ba8e-7938-436f-bcd3-0d7708010601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+ Add Resources </value>
      <webElementGuid>0fd03a8a-aa72-4829-849a-b498b3bf2d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-admin-layout[1]/div[@class=&quot;bootstrap-wrapper cus-fixed&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/app-ewr[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ewr-content&quot;]/div[@class=&quot;col-md-12 custom cus-pager&quot;]/div[@class=&quot;action-header&quot;]/div[@class=&quot;right&quot;]/div[2]/button[@class=&quot;item-1 left-20 k-button k-primary ng-star-inserted k-state-focused&quot;]</value>
      <webElementGuid>1d0781cd-7f67-4cc2-bae9-75ceba812839</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export Excel'])[1]/following::button[1]</value>
      <webElementGuid>e7e998a4-25f6-44e6-8195-a369c7b019d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::button[2]</value>
      <webElementGuid>efa37031-cf24-4db9-9040-19db733f6be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Requests'])[1]/preceding::button[1]</value>
      <webElementGuid>7e572ea4-7d2b-4c7e-94fc-90dce2cc9ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Resources']/parent::*</value>
      <webElementGuid>dc1c9aed-2f00-4ff1-a2fe-06e20ba86a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>216cc0e4-fdd4-47f6-b04e-5866a4940a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '+ Add Resources ' or . = '+ Add Resources ')]</value>
      <webElementGuid>e7b0fb3d-215a-4bee-8ca3-bc0c7d5fddc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
