<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Failed Message</name>
   <tag></tag>
   <elementGuidId>fcfdeb7e-0319-4ed3-a1b7-5a4612d7b25d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;basic-info&quot;]/app-basic-info/div/form/div/div/div[2]/div/div/div/div[1]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.email-error.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d3ec4f4b-3232-4691-8fac-abe217115e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>email-error ng-star-inserted</value>
      <webElementGuid>11acf6ca-7b55-4bd1-b0ca-87244f90c83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Failed! The email address has already registered for this event. </value>
      <webElementGuid>fddf8032-2c5b-4271-a0bb-0270c0eb0dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic-info&quot;)/app-basic-info[1]/div[@class=&quot;bootstrap-wrapper&quot;]/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;row kd-custom&quot;]/div[@class=&quot;col-md-12 basic-info&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 email&quot;]/div[@class=&quot;email-error ng-star-inserted&quot;]</value>
      <webElementGuid>88fd0a72-dd53-42f1-8fc8-509333ffb818</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='basic-info']/app-basic-info/div/form/div/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>2620c98d-1f2d-4436-9adb-ccb28cdeef5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[1]</value>
      <webElementGuid>046c0a91-8f91-445e-86bd-9597718b4fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::div[1]</value>
      <webElementGuid>d82c66be-c7e4-4a56-9785-db8ec59d2efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Failed! The email address has already registered for this event.']/parent::*</value>
      <webElementGuid>48cd7d8a-d108-4b1a-b11d-c1f39e30b53c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>9591c506-af01-440f-98a5-b49375a48d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Failed! The email address has already registered for this event. ' or . = ' Failed! The email address has already registered for this event. ')]</value>
      <webElementGuid>c70cd9d8-31e6-426e-83ff-b57c6ee77bbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
