<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_EWRApproveExecution</name>
   <tag></tag>
   <elementGuidId>a1065d63-5186-47a3-af7d-eb44a381cadb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='k-tabstrip-tabpanel-0']/div/kendo-grid/div/kendo-grid-list/div/div/table/tbody/tr[3]/td[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aa4afd3d-3b86-4569-93af-f65d2670d42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>a5a109e2-706f-467f-a6f0-a207550eefd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> EWRApproveExecution </value>
      <webElementGuid>753c3e65-d3b3-44cf-916d-d1cec00ca617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-tabstrip-tabpanel-0&quot;)/div[@class=&quot;user-listing ng-star-inserted&quot;]/kendo-grid[@class=&quot;custom-grid k-widget k-grid ng-star-inserted&quot;]/div[@class=&quot;k-grid-aria-root&quot;]/kendo-grid-list[@class=&quot;k-grid-container ng-star-inserted&quot;]/div[@class=&quot;k-grid-content k-virtual-content&quot;]/div[@class=&quot;k-grid-table-wrap&quot;]/table[@class=&quot;k-grid-table&quot;]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;k-touch-action-auto ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>513cb847-fe38-40d8-b98e-7614466567e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='k-tabstrip-tabpanel-0']/div/kendo-grid/div/kendo-grid-list/div/div/table/tbody/tr[3]/td[2]/div</value>
      <webElementGuid>4e66ed80-dcb2-42ac-8890-af353b297908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXECUTION'])[2]/following::div[2]</value>
      <webElementGuid>7595e94c-11a5-4815-9474-6d3ecc90394d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtask Updater 2Subtask Verifier 2'])[1]/following::div[3]</value>
      <webElementGuid>98a198d8-9d73-4493-acbf-497cdceed426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EWRApproveExecution'])[2]/preceding::div[1]</value>
      <webElementGuid>ddb8e16a-2d0a-4a3a-8586-70782b7cba5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXECUTION'])[3]/preceding::div[2]</value>
      <webElementGuid>04d8c7d6-d1f3-493d-891c-e004b1b6f751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='EWRApproveExecution']/parent::*</value>
      <webElementGuid>99ef4e41-bbae-4ef3-b07d-9598afbfc080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div</value>
      <webElementGuid>fe948cdf-6c53-4502-b28a-30139d00b537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' EWRApproveExecution ' or . = ' EWRApproveExecution ')]</value>
      <webElementGuid>ec3d7536-4fd6-4a14-8e2d-3ec694c52fe4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
