<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Failed The email address has already re_8eb43f</name>
   <tag></tag>
   <elementGuidId>fcfdeb7e-0319-4ed3-a1b7-5a4612d7b25d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='basic-info']/app-basic-info/div/form/div/div/div[2]/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.email-error.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>220cebc8-ade5-413e-b8be-18f8da2a8df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>email-error ng-star-inserted</value>
      <webElementGuid>fc6d0c35-4b8c-401f-8fb3-352ea72acfdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Failed! The email address has already registered for this event. </value>
      <webElementGuid>d91503b7-c432-45e7-bc1a-979c7e3bcbf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic-info&quot;)/app-basic-info[1]/div[@class=&quot;bootstrap-wrapper&quot;]/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;row kd-custom&quot;]/div[@class=&quot;col-md-12 basic-info&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 email&quot;]/div[@class=&quot;email-error ng-star-inserted&quot;]</value>
      <webElementGuid>13862cb0-ae58-4151-b174-a190968a0429</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='basic-info']/app-basic-info/div/form/div/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>31f36c1c-7c73-4294-b50a-9bb210f6512e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[1]</value>
      <webElementGuid>f1dad6db-6f41-482c-9aa9-b2ce78faadb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::div[1]</value>
      <webElementGuid>79a74723-f9d5-4798-9b2c-0dbe80c654b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Failed! The email address has already registered for this event.']/parent::*</value>
      <webElementGuid>5e98eefd-20ad-4a2a-be18-1d79dec98bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>3a876474-d054-40da-916e-690cc57a1dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Failed! The email address has already registered for this event. ' or . = ' Failed! The email address has already registered for this event. ')]</value>
      <webElementGuid>615b202e-e967-4e76-922c-a98ac21066f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
