<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Admin Homepage</name>
   <tag></tag>
   <elementGuidId>095f28e6-2bfd-494e-8555-49c7d174c8bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='4c35bb4d-1b40-4c4e-9cdb-ecec3f7ecf33']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#4c35bb4d-1b40-4c4e-9cdb-ecec3f7ecf33 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>61a8cece-f192-4eff-8d84-9e9be93c95a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin Homepage </value>
      <webElementGuid>eb43a943-91d8-4835-881e-9b22d3aedb95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4c35bb4d-1b40-4c4e-9cdb-ecec3f7ecf33&quot;)/div[1]</value>
      <webElementGuid>8c304cc1-7bac-41a1-8d7e-04274d060ecf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='4c35bb4d-1b40-4c4e-9cdb-ecec3f7ecf33']/div</value>
      <webElementGuid>fbe0529d-9e13-41bd-be04-73c6e2cc7be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Notifications (0)'])[1]/preceding::div[1]</value>
      <webElementGuid>42d2e1b7-1aea-4c0a-be6a-ca5c920240d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No notification'])[1]/preceding::div[2]</value>
      <webElementGuid>63bd6f80-223b-460d-b902-7df4d50be905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Admin Homepage']/parent::*</value>
      <webElementGuid>49d66ee7-c1e9-49df-8833-3026e4ea9893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div</value>
      <webElementGuid>e781231c-e5f5-4712-92b3-8aedd6ac4385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Admin Homepage ' or . = 'Admin Homepage ')]</value>
      <webElementGuid>aa846c09-b9b4-4402-9ab7-c484a029190c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
