<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_User Management</name>
   <tag></tag>
   <elementGuidId>daa0dd09-2bdc-43f5-9ffe-cd2ed4e9f28c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sub-89929f77-3cf0-4223-8231-08da655b00c5']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sub-89929f77-3cf0-4223-8231-08da655b00c5 > div.subtitle > div.sub-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>248607d4-3800-4846-b1fd-1ee38d17fd99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-title</value>
      <webElementGuid>e373c5aa-cc83-444d-83d4-133b9ddfdd8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> User Management </value>
      <webElementGuid>86814468-2b0c-4f3a-a698-de7b5d1bf300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sub-89929f77-3cf0-4223-8231-08da655b00c5&quot;)/div[@class=&quot;subtitle&quot;]/div[@class=&quot;sub-title&quot;]</value>
      <webElementGuid>3cdef6f1-c7c6-4c31-829a-6c40f1b487d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='sub-89929f77-3cf0-4223-8231-08da655b00c5']/div/div[2]</value>
      <webElementGuid>bafea020-92bd-4432-96b5-1b76d6dabc9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role Management'])[2]/following::div[5]</value>
      <webElementGuid>bc4f7161-8cce-42b0-b123-44247c959306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event Registration'])[2]/following::div[10]</value>
      <webElementGuid>2f7bc4d3-dc57-4727-ad04-2611ee136538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Data'])[4]/preceding::div[4]</value>
      <webElementGuid>d9aac9a8-8930-4df5-ae15-cd27e5cd55b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CSAT Summary'])[2]/preceding::div[9]</value>
      <webElementGuid>127c6fb7-30c4-454a-9239-f8d0f3832e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/a[3]/div/div[2]</value>
      <webElementGuid>e52d289b-b7f2-497b-8e0a-2e5bcbaa7b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' User Management ' or . = ' User Management ')]</value>
      <webElementGuid>4651fd8e-26ce-4cc1-ab21-eddec07533dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
