<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_opu  PPTSB Event Jump Event Planning Mo_5a1ddc</name>
   <tag></tag>
   <elementGuidId>b520f3c0-bd18-4c2d-a34c-918d287ecc34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='project-detail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#project-detail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>77657461-4c8f-457a-80c0-e86010a08da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>project-detail</value>
      <webElementGuid>7cda3dc2-7353-4a48-a51f-165073e1d8aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card</value>
      <webElementGuid>757fb84f-c4b8-4290-a88e-c5be2d111574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>opu  PPTSB Event Jump Event Planning ModuleExecution ModuleMilestone ModuleRoleNo Roles, yet.Add new Role by clicking Add new role button Add new role </value>
      <webElementGuid>9f22c5d1-d6d3-44c0-90b0-d3c747c14e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;project-detail&quot;)</value>
      <webElementGuid>14cbce47-41c9-4b87-92c4-39fc956866c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='project-detail']</value>
      <webElementGuid>cc8749ce-d1a2-4331-b1fb-a3e4da6d5393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTACT NUMBER'])[1]/following::div[1]</value>
      <webElementGuid>e5d18cfa-ad4c-4278-af72-432d57463af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[2]</value>
      <webElementGuid>0f25cd8d-045b-47ef-babf-ebc7a991c089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]</value>
      <webElementGuid>e1a5d964-7013-4888-9f12-02653581f75d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'project-detail' and (text() = 'opu  PPTSB Event Jump Event Planning ModuleExecution ModuleMilestone ModuleRoleNo Roles, yet.Add new Role by clicking Add new role button Add new role ' or . = 'opu  PPTSB Event Jump Event Planning ModuleExecution ModuleMilestone ModuleRoleNo Roles, yet.Add new Role by clicking Add new role button Add new role ')]</value>
      <webElementGuid>6c50b6ea-aa5d-4a58-ab6b-a4a333e50f57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
