<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CDU_k-checkbox - 2</name>
   <tag></tag>
   <elementGuidId>721c33ff-b1ce-47f8-8fd0-90bb20d59480</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/dialog-holder/dialog-wrapper/div/app-location-edit-model/div/div/div[2]/div/div[4]/kendo-expansionpanel/div[1]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.k-checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>341d79ad-e46b-4c26-84db-60b0edf39fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>229acc2b-b22d-4dd5-a1a6-65488865be6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-checkbox</value>
      <webElementGuid>80d1842a-5472-4485-a21e-8618822e8ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-tns-0-1&quot;]/dialog-holder[1]/dialog-wrapper[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal fade show in&quot;]/app-location-edit-model[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-dialog ng-star-inserted&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;location-container&quot;]/div[@class=&quot;location-item ng-star-inserted&quot;]/kendo-expansionpanel[@class=&quot;main-container k-expander ng-star-inserted&quot;]/div[@class=&quot;k-expander-header&quot;]/div[@class=&quot;ng-star-inserted&quot;]/input[@class=&quot;k-checkbox&quot;]</value>
      <webElementGuid>4497ef9d-b7cd-4220-a2ec-996cb2c66667</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='checkbox']</value>
      <webElementGuid>7d6e58d5-c419-496f-b033-94cfc9cd84ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kendo-expansionpanel/div/div/input</value>
      <webElementGuid>241804a9-0387-46ae-8af2-5e988638f533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>6accc0b1-e828-46c0-82f0-97702c5b4f11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
