<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_emailentry - Copy</name>
   <tag></tag>
   <elementGuidId>06a309e3-afb4-4b15-b9c7-8bb077b68169</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#k-6d9b98b7-f719-427e-baf3-4987d24d7543</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;basic-info&quot;]/app-basic-info/div/form/div/div/div[2]/div/div/div/div[1]/kendo-autocomplete/kendo-searchbar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95e8fe80-99c9-4f30-a83e-da9dd353c5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>284347a7-9a7a-404b-9217-4e5872d1829f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>8e821adb-d83b-4c25-9ac9-8ce7fbc9ce95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>41183070-7fdf-4794-b3ca-525f4e817011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>233ec379-7229-4f87-861a-973d78c41352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>k-6d9b98b7-f719-427e-baf3-4987d24d7543</value>
      <webElementGuid>a2cf3a32-03c6-4520-8f99-47d1e004065f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter email and search</value>
      <webElementGuid>848926a7-25da-42bd-abff-01766f39c4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>88c1628f-7a03-437a-bcab-973f907d207e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>e8c961b3-8b51-4c2a-8d4e-d4b985cfa272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>a27b02d3-5de6-4cd9-b24a-6cfd027c182a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c03063b9-9879-44a9-be31-60f1345ad88d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3d74d56b-8e2d-4327-9ba2-d1c0e59f6665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dac07a0f-6681-4add-926f-522efc2c61cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>5ec726ba-9b7d-4cdf-a7e2-8d129b0b306b</value>
      <webElementGuid>543db63c-8410-4732-9a21-0fb863bd11d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>NO DATA FOUND</value>
      <webElementGuid>1cf50250-79d4-4194-8e7e-a2d827b9c79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-6d9b98b7-f719-427e-baf3-4987d24d7543&quot;)</value>
      <webElementGuid>27176e7b-b4e2-4b78-ba73-5b9abb161589</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='k-6d9b98b7-f719-427e-baf3-4987d24d7543']</value>
      <webElementGuid>b64546f7-91e6-48c1-b82a-793f94e78d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='basic-info']/app-basic-info/div/form/div/div/div[2]/div/div/div/div/kendo-autocomplete/kendo-searchbar/input</value>
      <webElementGuid>25716569-dd43-4ded-b675-0f24454cc437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kendo-searchbar/input</value>
      <webElementGuid>3731f8db-fd98-4904-bac8-fba681f4c8db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'k-6d9b98b7-f719-427e-baf3-4987d24d7543' and @placeholder = 'Enter email and search']</value>
      <webElementGuid>4be7f0a5-48d3-4dcc-b518-d668b1f2bc69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
