<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__checkbox k-checkbox k-checkbox-md k-_8e0ad3</name>
   <tag></tag>
   <elementGuidId>f7b8b2ac-9ea6-4169-92bd-c68bdb03c331</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='needManpower']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.checkbox.k-checkbox.k-checkbox-md.k-rounded-md.ng-untouched.ng-pristine.ng-invalid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>377de2da-70f2-481f-925c-1de6271999e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>needManpower</value>
      <webElementGuid>8d6f9949-6ca6-4e56-b7f3-59001b993b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>983f779e-26c8-4182-9ab7-c64a81450fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>needManpower</value>
      <webElementGuid>f232c3e9-ca89-4a7c-85e8-945e99036119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox k-checkbox k-checkbox-md k-rounded-md ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>2e11414f-bffe-45b0-90fe-bbcaa124ecaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;work-information&quot;)/app-work-information[1]/div[@class=&quot;bootstrap-wrapper ng-invalid ng-star-inserted ng-dirty ng-touched&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 col-lg-12&quot;]/div[@class=&quot;row kd-custom&quot;]/div[@class=&quot;col-md-12 ng-star-inserted&quot;]/div[1]/label[1]/input[@class=&quot;checkbox k-checkbox k-checkbox-md k-rounded-md ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>182d746e-c739-4c0f-b8fa-e5ce0d68837e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='needManpower']</value>
      <webElementGuid>2a2c41a8-b63d-4126-b41c-75a43d5a9252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='work-information']/app-work-information/div/div/div/div[2]/div/div[3]/div/label/input</value>
      <webElementGuid>9f993960-b502-4eb6-8d32-d5bc97e1d850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>11fdd014-8601-404b-aa31-c993580231b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>bae7d79d-3621-41e7-885f-22e7ac445772</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
