<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__k-91c7cafb-367d-4f10-983f-2feece96b264</name>
   <tag></tag>
   <elementGuidId>3af8bc4e-e8db-456f-a97a-6dc4ddf60c96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='k-91c7cafb-367d-4f10-983f-2feece96b264']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#k-91c7cafb-367d-4f10-983f-2feece96b264</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c5d1eb35-200b-4d27-aee1-db2815adca7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0b6aeb50-fc58-4f36-9c3f-97f603812dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>95e6878e-1e2c-4366-b94a-9f1f879ce2f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>2b88050a-041f-4d9d-adb8-d84f27098a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>70b7e226-ba12-4fdf-ad96-60c19b84ccd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>k-91c7cafb-367d-4f10-983f-2feece96b264</value>
      <webElementGuid>61b1ebe1-7f68-4b39-aa02-3129c4dbab4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter email and search</value>
      <webElementGuid>fd45210b-680b-4c9f-aa29-5f00fd3449c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d67d4605-101c-4fbf-84a7-e014d9170b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>496cc76d-43c6-4637-9f03-249c44d5d307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>94b7530c-0b94-4bf3-b991-20dbbbca3942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dcf3288e-6133-4ebf-8036-ce9d8d4466ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e6310c82-3d77-4fa3-87f5-bb2316094d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>39e4920a-4286-44ae-8fdf-33f91b36796c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>9ea57905-080b-49db-9203-4a0ae56eabf5</value>
      <webElementGuid>c9f7a65b-0126-42be-89a6-376c78a6b455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>NO DATA FOUND</value>
      <webElementGuid>73d4a68c-7026-4178-93f2-e1d05bb356b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-91c7cafb-367d-4f10-983f-2feece96b264&quot;)</value>
      <webElementGuid>ddceed91-a42b-4597-a0ad-a9dc9573ea1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='k-91c7cafb-367d-4f10-983f-2feece96b264']</value>
      <webElementGuid>e8b7e5bf-1f80-4116-af9c-a714adb58836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='basic-info']/app-basic-info/div/form/div/div/div[2]/div/div/div/div/kendo-autocomplete/kendo-searchbar/input</value>
      <webElementGuid>fbe104a4-8534-4309-96a3-41695e03da54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kendo-searchbar/input</value>
      <webElementGuid>a4befd66-3c75-4258-9698-2edbd7ea04b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'k-91c7cafb-367d-4f10-983f-2feece96b264' and @placeholder = 'Enter email and search']</value>
      <webElementGuid>b7dea18b-ec41-4697-a8d7-decb64e0ce33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
