<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_emailentry</name>
   <tag></tag>
   <elementGuidId>4d38fa5d-9115-4280-a228-602047f71239</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#k-6d9b98b7-f719-427e-baf3-4987d24d7543</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;basic-info&quot;]/app-basic-info/div/form/div/div/div[2]/div/div/div/div[1]/kendo-autocomplete/kendo-searchbar/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa6ca1e5-0d61-4d15-a270-d0d448f27056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ff04b1dc-f72d-4c67-9f61-e1e7f09f614e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>0845947c-097a-4b98-a80f-7d5bd2f3adc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>d13d8788-a796-4a91-bd2a-e908e9be0706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>331e138a-4591-4a8a-9200-5bace8d5d633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>k-6d9b98b7-f719-427e-baf3-4987d24d7543</value>
      <webElementGuid>b5f0e386-9313-46ff-a184-d61aeabb3050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter email and search</value>
      <webElementGuid>51b6bbe5-be60-4df3-92af-6b767c68a90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>405c297e-e588-4656-bb5e-57848869365a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>e9060925-2730-45e8-9001-1fe058da8ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>616dc6c9-22b9-4ec9-9611-552caed46f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dee0f9fa-6469-4a77-aec1-434c3ef88585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bacfb46c-eaa6-4f0f-ab03-0d53d2da6f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3e38e097-e8e2-4c66-800d-93b48602c7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>5ec726ba-9b7d-4cdf-a7e2-8d129b0b306b</value>
      <webElementGuid>9010e2be-77a0-4d96-8afa-4e90e3021a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>NO DATA FOUND</value>
      <webElementGuid>1903ece6-d34c-4955-a04d-2e413dc4e99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-6d9b98b7-f719-427e-baf3-4987d24d7543&quot;)</value>
      <webElementGuid>8c5bf9fe-c6d5-41a6-b089-7e203b74c051</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='k-6d9b98b7-f719-427e-baf3-4987d24d7543']</value>
      <webElementGuid>6f3571f1-f329-4178-82cf-a9bf052cd609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='basic-info']/app-basic-info/div/form/div/div/div[2]/div/div/div/div/kendo-autocomplete/kendo-searchbar/input</value>
      <webElementGuid>a70b5cea-4bd9-4bef-8e20-6209addc98a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kendo-searchbar/input</value>
      <webElementGuid>373b4779-dd51-4c5f-aff0-f0f8fe392d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'k-6d9b98b7-f719-427e-baf3-4987d24d7543' and @placeholder = 'Enter email and search']</value>
      <webElementGuid>e74c19a5-4d5c-4bda-bcbc-1da82c7ba110</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
