<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EWR - Approve Execution_styled-checkb_11637f</name>
   <tag></tag>
   <elementGuidId>8f741352-c1b5-44c8-85dc-b15a834a8665</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#styled-checkbox-2edda113-37bb-4cb2-90e2-473aa290b250</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='styled-checkbox-2edda113-37bb-4cb2-90e2-473aa290b250']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f70a2ca-2407-4fb9-bacb-cfb22fcd2bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f82e4c6f-1872-4f6a-be65-2cb659de1a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-checkbox custom-input</value>
      <webElementGuid>d13be68e-0a3a-437d-8ab2-0b97a959fa32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>styled-checkbox-2edda113-37bb-4cb2-90e2-473aa290b250</value>
      <webElementGuid>86887fb1-730a-4fe9-b528-8cffe02e6999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2edda113-37bb-4cb2-90e2-473aa290b250</value>
      <webElementGuid>69d4d14f-2317-464a-9b7a-82fdb42bf875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;styled-checkbox-2edda113-37bb-4cb2-90e2-473aa290b250&quot;)</value>
      <webElementGuid>898ccf12-641f-43ba-aff6-dfe8dcf0da78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='styled-checkbox-2edda113-37bb-4cb2-90e2-473aa290b250']</value>
      <webElementGuid>06cc285a-6d7d-4ad0-b6dd-4fb3fd81201d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/input</value>
      <webElementGuid>922389d3-4460-4a01-aa3f-d21ebde378a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'styled-checkbox-2edda113-37bb-4cb2-90e2-473aa290b250']</value>
      <webElementGuid>73fb385d-b05c-41f5-a8e2-d65449556a03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
