<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_All Planning access</name>
   <tag></tag>
   <elementGuidId>b272be71-1d7d-4716-9403-f8e4b8d49e7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='b4d0bdf6-aeee-4414-bdef-4afcb5849544-0484e7dc-8f72-4bb0-51d6-08dbd52494d5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b4d0bdf6-aeee-4414-bdef-4afcb5849544-0484e7dc-8f72-4bb0-51d6-08dbd52494d5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>f2d27f88-8700-41c9-ac4e-f8a61d371bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d0f7dc90-5779-4252-ae67-2a9b53a78d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>7b83b267-ccd1-4682-a766-5d11dff9bfee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4d0bdf6-aeee-4414-bdef-4afcb5849544-0484e7dc-8f72-4bb0-51d6-08dbd52494d5</value>
      <webElementGuid>254c701f-8c30-4030-aaa4-8a51ee7f59f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4990c195-f9e4-489b-8d2d-e79cf60c6ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f60aca3a-b2a8-495c-80a0-c1cf58cf53ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Planning access</value>
      <webElementGuid>e2979748-6188-4ec9-9d2e-600d9e005ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4d0bdf6-aeee-4414-bdef-4afcb5849544-0484e7dc-8f72-4bb0-51d6-08dbd52494d5&quot;)</value>
      <webElementGuid>d0deee57-4063-45a8-b4fa-fdad7305d87c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='b4d0bdf6-aeee-4414-bdef-4afcb5849544-0484e7dc-8f72-4bb0-51d6-08dbd52494d5']</value>
      <webElementGuid>a42f2855-400e-4377-9308-7636295a8cae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='55690db9-ac4d-48bd-87ac-5e68acdc9061']/li</value>
      <webElementGuid>f0ad88f4-06d7-4827-91f3-e2277c820113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select role'])[2]/following::li[1]</value>
      <webElementGuid>9add3058-8311-423c-b063-3deecafb6f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::li[1]</value>
      <webElementGuid>dea253ac-7891-45e8-9f2a-241859f94f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Okay'])[1]/preceding::li[1]</value>
      <webElementGuid>9a3dbff5-943f-405b-8211-7ad4e8270c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All Planning access']/parent::*</value>
      <webElementGuid>aa2e8e3a-696b-4a43-aae4-ec1f4d948274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kendo-list/div/ul/li</value>
      <webElementGuid>48f2ac86-6181-47a2-ad90-2349908a778d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'b4d0bdf6-aeee-4414-bdef-4afcb5849544-0484e7dc-8f72-4bb0-51d6-08dbd52494d5' and (text() = 'All Planning access' or . = 'All Planning access')]</value>
      <webElementGuid>4d8cd181-05c0-49f2-b826-ed7dc9a88ede</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
