<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Automation Testing</name>
   <tag></tag>
   <elementGuidId>35e52c5e-c7fe-4855-a8f6-a32fa0af3f3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;26f1d95e-216b-48c3-8c7f-62fafc558f2f&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#52f840d1-a780-41ce-8291-7306baf29f9c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>93545a60-267b-4a17-af92-3e53bb1bbd3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>8c5fc7cf-86ac-45c6-a7e2-262421b95bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>864f5e5d-e2fa-4eaf-af94-05480046cb58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>52f840d1-a780-41ce-8291-7306baf29f9c</value>
      <webElementGuid>79e59947-37b3-4c50-8e2b-80bb00095028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Demo - Execution</value>
      <webElementGuid>6c3a4acb-873c-4029-90c5-ffe01003a1ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;52f840d1-a780-41ce-8291-7306baf29f9c&quot;)</value>
      <webElementGuid>adde2e13-d883-4c2f-bd7e-49ff2076b218</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='52f840d1-a780-41ce-8291-7306baf29f9c']</value>
      <webElementGuid>b0f426b7-65f1-4dc0-97d7-bce959c1db23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-a12a4374-7c9c-4212-b99d-aa179dcdf6a1']/span</value>
      <webElementGuid>88e2bb78-581d-4c53-856d-31b4120ab8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/following::span[2]</value>
      <webElementGuid>d3a11827-a28e-43f7-8ae9-830aac2582af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Malaysia LNG Sdn Bhd'])[1]/following::span[4]</value>
      <webElementGuid>ac311075-dc1f-4404-9e49-141602d161a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[1]/preceding::span[3]</value>
      <webElementGuid>d8a4667a-5529-4790-8642-b9e7e9bb2a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Template'])[1]/preceding::span[4]</value>
      <webElementGuid>9349f3d9-e415-497a-b89c-27e10668176e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Demo - Execution']/parent::*</value>
      <webElementGuid>4434b8c6-6702-4d76-9d6c-1d6a17d27c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/kendo-dropdownlist/span/span</value>
      <webElementGuid>e438ee9f-0d63-43ab-b32f-2e29fb27079e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '52f840d1-a780-41ce-8291-7306baf29f9c' and (text() = 'Demo - Execution' or . = 'Demo - Execution')]</value>
      <webElementGuid>7150d2c1-1c59-4246-8316-f3fd12a93338</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
