<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_All Planning access</name>
   <tag></tag>
   <elementGuidId>b272be71-1d7d-4716-9403-f8e4b8d49e7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[text()='All Planning access']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b4d0bdf6-aeee-4414-bdef-4afcb5849544-0484e7dc-8f72-4bb0-51d6-08dbd52494d5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>05843356-41e9-4bfa-ab0b-4187f4de8951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ba505680-93b4-4e7f-8f24-cd80dc95a049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>e4fb399d-91d5-4e5c-8558-718932395d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4d0bdf6-aeee-4414-bdef-4afcb5849544-0484e7dc-8f72-4bb0-51d6-08dbd52494d5</value>
      <webElementGuid>b6ab36fb-6200-4b34-bab0-405c44c254ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>fb129e09-8cc1-478a-bfbf-5e89a96ea345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0e973be6-a3f7-46a6-80e0-79dbe4bb7b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Planning access</value>
      <webElementGuid>f64cad54-de59-4b2b-ad29-817b436a4b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4d0bdf6-aeee-4414-bdef-4afcb5849544-0484e7dc-8f72-4bb0-51d6-08dbd52494d5&quot;)</value>
      <webElementGuid>d59d77a0-7ae1-4d0f-b70e-a9e711cf12f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='b4d0bdf6-aeee-4414-bdef-4afcb5849544-0484e7dc-8f72-4bb0-51d6-08dbd52494d5']</value>
      <webElementGuid>863bb424-e50f-43d9-8358-7de730fe223c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='55690db9-ac4d-48bd-87ac-5e68acdc9061']/li</value>
      <webElementGuid>692522de-db4c-4201-a0b0-de295d64aa06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select role'])[2]/following::li[1]</value>
      <webElementGuid>9e327706-24b9-4a68-a978-0a476db56d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::li[1]</value>
      <webElementGuid>8d7be152-9f17-4d95-91fd-64a4197fedb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Okay'])[1]/preceding::li[1]</value>
      <webElementGuid>531dfcdb-f240-4294-b926-2c700aacd77d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All Planning access']/parent::*</value>
      <webElementGuid>c839900b-b387-4cf6-a38c-dc12cd80a20c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kendo-list/div/ul/li</value>
      <webElementGuid>9c4c7090-6b97-4d01-8c1b-e468b182bd87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'b4d0bdf6-aeee-4414-bdef-4afcb5849544-0484e7dc-8f72-4bb0-51d6-08dbd52494d5' and (text() = 'All Planning access' or . = 'All Planning access')]</value>
      <webElementGuid>cfa03183-245d-41b6-aa12-3d0698544dbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
