<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Demo - Planning</name>
   <tag></tag>
   <elementGuidId>9fafd247-7f0a-4fb4-8e08-2ad2f5c0605d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='13effc05-488c-47f6-bca6-8f19ce6144c7-d4fea33f-fe5c-4ea1-cc13-08dbe0cc2d77']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#13effc05-488c-47f6-bca6-8f19ce6144c7-d4fea33f-fe5c-4ea1-cc13-08dbe0cc2d77</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>dde102a1-c422-430d-a9ec-b985379ded0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>5e72f78d-f999-402f-a0e8-5002ebce480b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>945c9981-c580-4a25-b142-e381dc34bda1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>13effc05-488c-47f6-bca6-8f19ce6144c7-d4fea33f-fe5c-4ea1-cc13-08dbe0cc2d77</value>
      <webElementGuid>56832caa-b0a5-4c09-bf89-2158efac8541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5a3ffbd0-818f-4b10-aa0b-00ddd2dff687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>03653389-06f0-4945-9016-5916f2fbce42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Demo - Planning</value>
      <webElementGuid>7dc9dbec-6914-4d6a-9f08-616ccdc58c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;13effc05-488c-47f6-bca6-8f19ce6144c7-d4fea33f-fe5c-4ea1-cc13-08dbe0cc2d77&quot;)</value>
      <webElementGuid>66990861-be34-4b25-bd37-0c35c06a530b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='13effc05-488c-47f6-bca6-8f19ce6144c7-d4fea33f-fe5c-4ea1-cc13-08dbe0cc2d77']</value>
      <webElementGuid>ac9a711e-e59e-4dd2-8c91-d3d2d70402f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='d1a80757-5c8c-4521-a623-c17d1fe4b6f9']/li[2]</value>
      <webElementGuid>718b5003-5aa3-4d4d-ae28-c0bda1f76a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demo - Execution'])[2]/following::li[1]</value>
      <webElementGuid>c2b839f2-207f-4c1d-801f-285b9c41415a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/following::li[4]</value>
      <webElementGuid>275d6899-66a4-4dc7-9891-329ca7f23227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QA/QC Event'])[1]/preceding::li[1]</value>
      <webElementGuid>2df81fab-582c-48f5-81ef-f51e839e8f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Okay'])[1]/preceding::li[2]</value>
      <webElementGuid>ff8bb811-3499-4767-9bf7-8cd833adea40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Demo - Planning']/parent::*</value>
      <webElementGuid>c111dcf7-0b6f-4a8c-b0d4-c3c49ba95084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kendo-list/div/ul/li[2]</value>
      <webElementGuid>9b03dce4-6ccb-401d-8625-7ef83bbecac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '13effc05-488c-47f6-bca6-8f19ce6144c7-d4fea33f-fe5c-4ea1-cc13-08dbe0cc2d77' and (text() = 'Demo - Planning' or . = 'Demo - Planning')]</value>
      <webElementGuid>c4906075-2e6c-442c-9ba8-eec13a18b2ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
