<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Demo24</name>
   <tag></tag>
   <elementGuidId>7914b73f-366e-4b24-9d5d-db695f8f11e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//kendo-dropdownlist[@textfield='eventName']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#6fd4bc4f-e077-47be-950a-7a02e5745b8d-597d2883-997f-4b0f-7e6c-08dc74b2d28c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>3e4a89e9-6cf0-455f-aa82-21316b447e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c445e1c0-aa1c-44a8-a821-6bcb85b6c9e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>ab141cf8-e30e-4998-89d2-97056bef8fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>6fd4bc4f-e077-47be-950a-7a02e5745b8d-597d2883-997f-4b0f-7e6c-08dc74b2d28c</value>
      <webElementGuid>c5f0e80a-f102-479a-952d-8b33ca1d77c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>919b54db-312e-421d-9fe4-c89ee9db6fc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>d98c093c-5c17-4f4e-81bd-1dcf77271226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Demo24</value>
      <webElementGuid>4da74d01-578c-4af5-a458-82f4717cb5c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6fd4bc4f-e077-47be-950a-7a02e5745b8d-597d2883-997f-4b0f-7e6c-08dc74b2d28c&quot;)</value>
      <webElementGuid>1f0da368-10a0-4b42-9dd6-5db42058383f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='6fd4bc4f-e077-47be-950a-7a02e5745b8d-597d2883-997f-4b0f-7e6c-08dc74b2d28c']</value>
      <webElementGuid>71969b05-3abb-429b-876a-ae70c7eff134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='6a96da78-b9b6-4ca7-84d5-8df71ea3daad']/li[8]</value>
      <webElementGuid>d95d4753-4eb7-4949-9ccb-737da2fff770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEMO_SN'])[1]/following::li[1]</value>
      <webElementGuid>b19fa520-5425-4ce7-8222-c738b4f3b78f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEMO TGAST TA 2023'])[1]/following::li[2]</value>
      <webElementGuid>78c62c8d-1dbe-4d0d-9877-f0cb88cc6b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demo-Nayli'])[1]/preceding::li[1]</value>
      <webElementGuid>f44f4517-930f-4850-b1f8-fa48d8c4227a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EVENT - REGRESSION'])[1]/preceding::li[2]</value>
      <webElementGuid>e8e4845b-6a04-421d-9326-69279d5612b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Demo24']/parent::*</value>
      <webElementGuid>c9cdbb1e-27f7-475f-b7be-0767c5001820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]</value>
      <webElementGuid>bb96587b-4d5e-48d1-a752-493c113fabdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '6fd4bc4f-e077-47be-950a-7a02e5745b8d-597d2883-997f-4b0f-7e6c-08dc74b2d28c' and (text() = 'Demo24' or . = 'Demo24')]</value>
      <webElementGuid>bd831134-557c-4b8e-b9ef-06a379a15a59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
