<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Demo - Training</name>
   <tag></tag>
   <elementGuidId>bc57c4c4-82da-4b53-bc47-d5ccf3310312</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[text()='PETRONAS Penapisan Terengganu Sdn Bhd']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bc8a1793-e71d-49a9-a123-9f2425cde3cc-50b78678-0923-4ce4-0288-08dbf61a6eee</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e182dc8b-e29c-4e25-9fc8-78bf7db9a5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f097ac90-8098-4629-90c1-eefb839775f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>81331d6a-22a7-4acf-9517-61a152edffda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bc8a1793-e71d-49a9-a123-9f2425cde3cc-50b78678-0923-4ce4-0288-08dbf61a6eee</value>
      <webElementGuid>7b41f9c0-2357-4559-a34a-a30d95fdbd08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4f4f8fca-d712-4b73-bfb3-b515eca938e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>a525159a-5411-453c-b04e-a2af85bd2b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Demo - Training</value>
      <webElementGuid>47967f63-4eb2-4a49-b8f7-62b014eb15f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bc8a1793-e71d-49a9-a123-9f2425cde3cc-50b78678-0923-4ce4-0288-08dbf61a6eee&quot;)</value>
      <webElementGuid>23496869-f603-4ce8-b08c-2f4210cad61b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='bc8a1793-e71d-49a9-a123-9f2425cde3cc-50b78678-0923-4ce4-0288-08dbf61a6eee']</value>
      <webElementGuid>5595033a-6d2a-45b1-8e38-58845bbf5c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='259ca513-0e69-4ad2-aaa4-3b8df3ac3ef2']/li[8]</value>
      <webElementGuid>af01add1-003e-4939-9e68-d9bbbc4f36c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Testing'])[8]/following::li[1]</value>
      <webElementGuid>96fbbab9-c9f9-419b-88ce-46afc23cf34a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Testing'])[7]/following::li[2]</value>
      <webElementGuid>911407ad-6f27-45ba-990d-6e6e9b624233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEMO TGAST TA 2023'])[1]/preceding::li[1]</value>
      <webElementGuid>a34aadfe-c765-4332-87cf-ffd848505cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEMO_SN'])[1]/preceding::li[2]</value>
      <webElementGuid>c1f428f0-4e3e-4337-a142-506ae892b7ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Demo - Training']/parent::*</value>
      <webElementGuid>c3c45a10-7650-4c95-bfd3-081d9cd56a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]</value>
      <webElementGuid>017c14d8-c1bb-4e20-b6f5-efec08240ff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'bc8a1793-e71d-49a9-a123-9f2425cde3cc-50b78678-0923-4ce4-0288-08dbf61a6eee' and (text() = 'Demo - Training' or . = 'Demo - Training')]</value>
      <webElementGuid>cbf7aada-8ff3-4582-8c22-c74cd5fb19a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
