<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Demo</name>
   <tag></tag>
   <elementGuidId>768cb166-8e5b-4c08-991d-03cd033aef8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value> </value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a2ba9a4f-c20c-4fff-a47e-e4cf36648af8-897b260a-755e-4295-ab01-8d7fcc45cb9f</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5e086e6b-a2bb-4e03-9c89-0756d925f13b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>64aa75d2-92ab-4f0e-a171-d4ec36c5453c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-focused k-state-selected ng-star-inserted</value>
      <webElementGuid>b1c4f15f-cead-4461-bbcb-de1802e2566b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a2ba9a4f-c20c-4fff-a47e-e4cf36648af8-897b260a-755e-4295-ab01-8d7fcc45cb9f</value>
      <webElementGuid>bd9d3b37-b04e-431f-b40a-af182fd8d2c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>543a7ea4-f35e-442d-b835-a6efa25ac3d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b92ac29c-378f-4241-89b3-30afdb45a7e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Demo</value>
      <webElementGuid>c41c9980-a9df-4b47-9882-ce1c7249f16e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a2ba9a4f-c20c-4fff-a47e-e4cf36648af8-897b260a-755e-4295-ab01-8d7fcc45cb9f&quot;)</value>
      <webElementGuid>365c18f5-96aa-4e92-8c91-641fcabb4e71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='a2ba9a4f-c20c-4fff-a47e-e4cf36648af8-897b260a-755e-4295-ab01-8d7fcc45cb9f']</value>
      <webElementGuid>939947dd-81be-4a07-a79a-364064793e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='e498c968-f95d-4550-ae6f-21c00631e9d2']/li</value>
      <webElementGuid>b3e6b8fc-a4e0-42ec-93a1-bce37ef6cbe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/following::li[1]</value>
      <webElementGuid>5a5220fa-4cca-4e24-a790-aa010eea130a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='items per page'])[1]/following::li[1]</value>
      <webElementGuid>1884a1b4-9c80-464f-963e-e5c1649999b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Malaysia LNG Sdn Bhd'])[1]/preceding::li[1]</value>
      <webElementGuid>4a72a7d5-15f8-410a-8d9d-eebd06d5e03a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Malaysian Refining Company Sdn Bhd'])[1]/preceding::li[2]</value>
      <webElementGuid>271cd68b-82b9-47ad-9955-8e16868e143e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kendo-list/div/ul/li</value>
      <webElementGuid>14c352c3-b8d5-476f-8b73-fd6607dca87c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'a2ba9a4f-c20c-4fff-a47e-e4cf36648af8-897b260a-755e-4295-ab01-8d7fcc45cb9f' and (text() = 'Demo' or . = 'Demo')]</value>
      <webElementGuid>720a157c-ab32-4f9f-a73c-c15d2f1aed04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='4cb88b4e-d421-457e-88c1-82c0de69405d-897b260a-755e-4295-ab01-8d7fcc45cb9f']</value>
      <webElementGuid>fa41a23d-4b8f-4634-85e8-9a35fb9a1c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='aaab877e-87a5-4816-b08f-c9527c98f1cb']/li</value>
      <webElementGuid>f2eb56a5-de4f-4fa3-aad0-ade621194f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '4cb88b4e-d421-457e-88c1-82c0de69405d-897b260a-755e-4295-ab01-8d7fcc45cb9f' and (text() = 'Demo' or . = 'Demo')]</value>
      <webElementGuid>b6a9dee2-33a9-46cf-85af-39d2e99dbfbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
