<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_gttt</name>
   <tag></tag>
   <elementGuidId>ea84c09a-3133-4666-aac5-06a49129f33b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[text()=' gttt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#be8a9f00-8625-4e31-96e6-40b91676c51a-6ab84d22-ff5e-49b2-ff9b-08dc844af254</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>57194059-617d-4b1a-aa25-90c30070c456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>5bea6e00-3dbe-4c9c-a4ca-f6dc8319c0a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-focused ng-star-inserted</value>
      <webElementGuid>5dc15ea7-bf66-4588-a5f4-41d3a820e4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>be8a9f00-8625-4e31-96e6-40b91676c51a-6ab84d22-ff5e-49b2-ff9b-08dc844af254</value>
      <webElementGuid>5036f944-031d-4b69-9081-0207b625d689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c843db4e-c448-4044-bbb3-60abf995bbc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e2012776-bcfa-433f-8d66-d0391416b4a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> gttt</value>
      <webElementGuid>23508b9c-a5e4-4154-8694-1889b9571a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;be8a9f00-8625-4e31-96e6-40b91676c51a-6ab84d22-ff5e-49b2-ff9b-08dc844af254&quot;)</value>
      <webElementGuid>ebd53bd3-8ee6-48b9-9a7e-7c6a80f43577</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='be8a9f00-8625-4e31-96e6-40b91676c51a-6ab84d22-ff5e-49b2-ff9b-08dc844af254']</value>
      <webElementGuid>b590599f-3595-4b90-890a-fda3fa8283e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='f80ce00b-ee0c-4f3e-86ed-25d92e797d8f']/li</value>
      <webElementGuid>77c0272c-1963-4bc0-bf1f-0fac19f5ce74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::li[1]</value>
      <webElementGuid>455ffc4b-d0e6-4c12-93d0-eafc350c1e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save As Draft'])[1]/following::li[1]</value>
      <webElementGuid>95938188-8600-4e70-9dbf-53a31cde6f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Okay'])[1]/preceding::li[1]</value>
      <webElementGuid>57d4bd01-d63f-4ce9-aaae-d19dff2a6369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='gttt']/parent::*</value>
      <webElementGuid>240283b2-1841-4d1b-87c0-fe1632e61b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li</value>
      <webElementGuid>5634669d-4750-4432-a8b1-e25abcab0074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'be8a9f00-8625-4e31-96e6-40b91676c51a-6ab84d22-ff5e-49b2-ff9b-08dc844af254' and (text() = ' gttt' or . = ' gttt')]</value>
      <webElementGuid>9d2f7abf-1720-4cb3-8178-4ef7f3f2959e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
