<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_GHH</name>
   <tag></tag>
   <elementGuidId>ecfc5195-89d7-4a21-aa2d-a3df6a438ad3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[text()='13']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#7ec98d78-b663-479e-b63e-1a87f29083fd-bda97f16-b3d5-4eba-4b07-08dc8b5f789f</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c32ed8a1-7295-4439-bac1-ce8c0c232e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d06b247d-678a-4b43-a2a1-ea82c7ed950e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>e6d3a188-596e-46bb-93f0-6b261349aca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>7ec98d78-b663-479e-b63e-1a87f29083fd-bda97f16-b3d5-4eba-4b07-08dc8b5f789f</value>
      <webElementGuid>bf728ced-b903-432b-aa73-2b8dd02a07be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f5d3310d-353a-42ad-9e4a-288f2d12eb22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b7e33718-21ca-4ebe-881e-8193c891339e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GHH</value>
      <webElementGuid>c0b20023-f1cd-4629-bb44-bf99d5a967d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;7ec98d78-b663-479e-b63e-1a87f29083fd-bda97f16-b3d5-4eba-4b07-08dc8b5f789f&quot;)</value>
      <webElementGuid>b41b0e2b-f84f-461c-820d-e8ca0f84c6b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='7ec98d78-b663-479e-b63e-1a87f29083fd-bda97f16-b3d5-4eba-4b07-08dc8b5f789f']</value>
      <webElementGuid>b750db28-692a-42b1-ae77-ce7cfbab2a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='8fc66b09-9019-4058-83a9-e015cb553d61']/li[2]</value>
      <webElementGuid>6e01295b-7e11-470d-ac6c-9bcf205da0c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dve'])[1]/following::li[1]</value>
      <webElementGuid>a29b0e04-0443-411e-b189-795908a8d500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::li[2]</value>
      <webElementGuid>7b5af306-d6c7-4aad-9e99-0453f496266c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OKOKOJO2'])[1]/preceding::li[1]</value>
      <webElementGuid>321ad921-7ab1-4034-b924-6fe3530f70e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rreer'])[1]/preceding::li[2]</value>
      <webElementGuid>8d758be3-2470-4616-9720-a6ee3a9d7fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='GHH']/parent::*</value>
      <webElementGuid>af53567e-bf2b-490b-8e81-110b43d33bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li[2]</value>
      <webElementGuid>0ff42831-2cad-4828-8925-61b653110f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '7ec98d78-b663-479e-b63e-1a87f29083fd-bda97f16-b3d5-4eba-4b07-08dc8b5f789f' and (text() = 'GHH' or . = 'GHH')]</value>
      <webElementGuid>b6091cd1-927b-4d9c-8966-ab4fafd77a97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
