<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_GHH</name>
   <tag></tag>
   <elementGuidId>ecfc5195-89d7-4a21-aa2d-a3df6a438ad3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[text()='GHH']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#7ec98d78-b663-479e-b63e-1a87f29083fd-bda97f16-b3d5-4eba-4b07-08dc8b5f789f</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>9bf8aac0-e481-4b03-bbf9-0c78d1b976cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>2df8173f-e538-431a-a5d8-57328507e180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>512dec4a-dd6c-42dc-9a3c-019565943e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>7ec98d78-b663-479e-b63e-1a87f29083fd-bda97f16-b3d5-4eba-4b07-08dc8b5f789f</value>
      <webElementGuid>6fb138ed-d989-4d7c-bd24-550a87f8ca74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>67e8f5e4-4ef9-4ffb-98c4-e573295ca3f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>dc6850ce-92fc-4067-8026-599f72b44578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GHH</value>
      <webElementGuid>63003150-f31d-4ce7-9648-0c3b89fa0861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;7ec98d78-b663-479e-b63e-1a87f29083fd-bda97f16-b3d5-4eba-4b07-08dc8b5f789f&quot;)</value>
      <webElementGuid>f18aada1-7313-4820-bce9-b077f70184a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='7ec98d78-b663-479e-b63e-1a87f29083fd-bda97f16-b3d5-4eba-4b07-08dc8b5f789f']</value>
      <webElementGuid>3423d0f2-e66f-4978-8863-9eb49ad932b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='8fc66b09-9019-4058-83a9-e015cb553d61']/li[2]</value>
      <webElementGuid>71daff5c-5434-42cf-aec8-7239bd99f59e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dve'])[1]/following::li[1]</value>
      <webElementGuid>15589f6f-41f1-41a9-a32b-a23871ca1c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::li[2]</value>
      <webElementGuid>a696098c-5c23-4dd8-88d8-96b26ed4ef7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OKOKOJO2'])[1]/preceding::li[1]</value>
      <webElementGuid>71109708-7739-448c-80fe-77278b1377a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rreer'])[1]/preceding::li[2]</value>
      <webElementGuid>3bb2d186-ceae-4ec2-a500-0d92593a0c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='GHH']/parent::*</value>
      <webElementGuid>478bdfbb-3b80-4189-a7a6-93519c21d5a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li[2]</value>
      <webElementGuid>b31e46f5-dd64-4f96-9b2e-c04ef517cb15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '7ec98d78-b663-479e-b63e-1a87f29083fd-bda97f16-b3d5-4eba-4b07-08dc8b5f789f' and (text() = 'GHH' or . = 'GHH')]</value>
      <webElementGuid>cb13fdcd-ba37-4de3-ba3c-c56d1fd9be7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
