<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_gttt</name>
   <tag></tag>
   <elementGuidId>ea84c09a-3133-4666-aac5-06a49129f33b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[text()='1A']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#be8a9f00-8625-4e31-96e6-40b91676c51a-6ab84d22-ff5e-49b2-ff9b-08dc844af254</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a11467ba-3d18-4692-bc0e-c26193688226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>edbc08fe-ebde-45bb-b57e-2bb0373f33f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-focused ng-star-inserted</value>
      <webElementGuid>a2360812-ae95-4feb-8e28-c4055035ddaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>be8a9f00-8625-4e31-96e6-40b91676c51a-6ab84d22-ff5e-49b2-ff9b-08dc844af254</value>
      <webElementGuid>80f858b9-bbe5-4543-95cf-1f903d3f36c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2f75ef52-810d-47da-829c-63226a7b7350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5aab4737-3541-4618-8b90-25dd58baae08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> gttt</value>
      <webElementGuid>79745fbb-72e0-40ac-8070-0bf7ea5a71ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;be8a9f00-8625-4e31-96e6-40b91676c51a-6ab84d22-ff5e-49b2-ff9b-08dc844af254&quot;)</value>
      <webElementGuid>00fdcf4a-2a64-4289-ad88-28bb95cd5af2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='be8a9f00-8625-4e31-96e6-40b91676c51a-6ab84d22-ff5e-49b2-ff9b-08dc844af254']</value>
      <webElementGuid>8b5c0ff9-aca4-4921-b1c7-62263fc03d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='f80ce00b-ee0c-4f3e-86ed-25d92e797d8f']/li</value>
      <webElementGuid>51726530-6f76-4994-bafc-acc81a1b90e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::li[1]</value>
      <webElementGuid>335f18b1-2a28-4b80-94a4-40470b7828f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save As Draft'])[1]/following::li[1]</value>
      <webElementGuid>0c2a12c8-7b50-4398-94d5-706c06d2f519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Okay'])[1]/preceding::li[1]</value>
      <webElementGuid>bf0d09d3-11ca-4b7f-82b2-20572d984f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='gttt']/parent::*</value>
      <webElementGuid>d9dab4c5-c3de-4dc9-99cd-28c1fabe173a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li</value>
      <webElementGuid>dceda250-4673-49e7-96ea-a1d4e7bb8263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'be8a9f00-8625-4e31-96e6-40b91676c51a-6ab84d22-ff5e-49b2-ff9b-08dc844af254' and (text() = ' gttt' or . = ' gttt')]</value>
      <webElementGuid>0163fbda-054f-4c88-85e9-95823944a13f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
