<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Jump Event</name>
   <tag></tag>
   <elementGuidId>cc177258-c2a3-4800-87e3-a2d4b6e29b29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[text()='Jump Event']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b8cd8ce7-ba2f-4def-abf1-fd64abc11614-6064bbae-5160-479d-6f0b-08dbd5239f26</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>25e20bfe-79ec-4c95-bc47-fd5f865087e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>a32fa189-6fa9-4bbf-b575-ad7c7bc2a922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>ae0a7940-61db-41c1-9f14-b32422ee21ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b8cd8ce7-ba2f-4def-abf1-fd64abc11614-6064bbae-5160-479d-6f0b-08dbd5239f26</value>
      <webElementGuid>d238c43b-5cac-4d1d-9549-c02b3f79abf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>abd3c1df-4ac7-4d39-9c68-750b841bdbde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>067f2f9c-26f4-42a7-b2d8-dc44609faf54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jump Event</value>
      <webElementGuid>851791da-9254-4a68-a0fb-9d110759e66e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b8cd8ce7-ba2f-4def-abf1-fd64abc11614-6064bbae-5160-479d-6f0b-08dbd5239f26&quot;)</value>
      <webElementGuid>eade8892-b05a-48d1-b95f-9180b91f247d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='b8cd8ce7-ba2f-4def-abf1-fd64abc11614-6064bbae-5160-479d-6f0b-08dbd5239f26']</value>
      <webElementGuid>0f1d6fae-c792-4122-b51f-a882e7b2b294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='e5b550a3-3528-461a-afd2-803090113e8d']/li[12]</value>
      <webElementGuid>cd7d69f3-e254-42d5-90de-3f54235fb0f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exec Event01'])[1]/following::li[1]</value>
      <webElementGuid>634c3ddb-4e4f-4bed-9f54-5a74343281d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exec Event'])[1]/following::li[2]</value>
      <webElementGuid>e3a3f3f7-0899-4a3a-8e46-efeac773466b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mech Event'])[1]/preceding::li[1]</value>
      <webElementGuid>bda26f16-951b-4adb-a18a-4e7ea5b97633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Event 2023'])[1]/preceding::li[2]</value>
      <webElementGuid>10ba8784-ef98-42d5-8e79-9611d195c658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jump Event']/parent::*</value>
      <webElementGuid>116d9fdc-7356-4897-af50-5e652f291fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[12]</value>
      <webElementGuid>95644d33-de5d-472b-8768-c65a7fd70c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'b8cd8ce7-ba2f-4def-abf1-fd64abc11614-6064bbae-5160-479d-6f0b-08dbd5239f26' and (text() = 'Jump Event' or . = 'Jump Event')]</value>
      <webElementGuid>591a15b5-4019-4c70-b445-73fe02678166</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
