<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Malaysia LNG Sdn Bhd</name>
   <tag></tag>
   <elementGuidId>f529ab6d-eb0d-45c8-9c44-8681cc39651f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//kendo-dropdownlist[@textfield='opuName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ae48afe5-7896-4df3-9e34-f2055c448e4d-12e07b18-746c-4ccf-a2b2-e9cebd1c2b7b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e8a5fc01-531f-41c4-886c-396516cddc0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>78b77cbd-96e8-45f6-aa0e-2239206dabb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>8ada8b30-86bd-454d-8f8b-d429b353524c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ae48afe5-7896-4df3-9e34-f2055c448e4d-12e07b18-746c-4ccf-a2b2-e9cebd1c2b7b</value>
      <webElementGuid>095528e7-765b-4ba0-8784-3bba6775d7bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3095991e-103f-4eb5-889d-9156f9c81088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1957253a-b94a-46fd-9fa7-2af71832db5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Malaysia LNG Sdn Bhd</value>
      <webElementGuid>0d9ac391-7b73-4f21-af5a-216ff244305c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ae48afe5-7896-4df3-9e34-f2055c448e4d-12e07b18-746c-4ccf-a2b2-e9cebd1c2b7b&quot;)</value>
      <webElementGuid>3f73c272-7c3f-43f8-8ebc-993cbaefd61b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='ae48afe5-7896-4df3-9e34-f2055c448e4d-12e07b18-746c-4ccf-a2b2-e9cebd1c2b7b']</value>
      <webElementGuid>51fdd768-6f73-4427-acdd-c54c159bc304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='c886e847-d357-4774-88b4-88713f1389b6']/li[2]</value>
      <webElementGuid>d533bc7a-57bf-4dee-a55a-bff1c6da4694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demo'])[2]/following::li[1]</value>
      <webElementGuid>d0a96cf4-4f8f-42d1-bb7d-9990d5526130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/following::li[2]</value>
      <webElementGuid>752dee50-e06c-452f-9dc9-37a729f53b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Malaysian Refining Company Sdn Bhd'])[1]/preceding::li[1]</value>
      <webElementGuid>6a23f27c-e389-415c-9e76-6a1391117302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PC Ammonia Sdn Bhd'])[1]/preceding::li[2]</value>
      <webElementGuid>e91b09d2-3e7b-4796-a350-3e04591838d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Malaysia LNG Sdn Bhd']/parent::*</value>
      <webElementGuid>bd7333f6-acb5-41d4-bcc7-208d059e0b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kendo-list/div/ul/li[2]</value>
      <webElementGuid>b1db3eb0-f261-4207-bba3-6145d65df646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'ae48afe5-7896-4df3-9e34-f2055c448e4d-12e07b18-746c-4ccf-a2b2-e9cebd1c2b7b' and (text() = 'Malaysia LNG Sdn Bhd' or . = 'Malaysia LNG Sdn Bhd')]</value>
      <webElementGuid>dec011bc-5a75-4fc6-9cb4-851377a2b728</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
