<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Maintenance</name>
   <tag></tag>
   <elementGuidId>49d2a397-ef39-4679-95aa-3dd47a1a2040</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[text()='Maintenance']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#9df3ae2d-b741-4dc9-a624-40639976ce83-e63ab19d-37d2-4968-aaf0-26d1b86494fb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>cd367c1d-1865-4d68-92ec-888296cf3728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>5684741e-e6eb-494c-9fae-b70146b45ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>a2f2c16f-dfc4-4fb3-a7b4-43dd7f9a027e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9df3ae2d-b741-4dc9-a624-40639976ce83-e63ab19d-37d2-4968-aaf0-26d1b86494fb</value>
      <webElementGuid>7431061c-7d7a-402a-8c63-94561c6245a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>38674124-5598-4985-b84f-37a6dd62f991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>2c113df1-57b8-4f14-97f9-ce1b4c9f58bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Maintenance</value>
      <webElementGuid>b4bceedb-9d66-4090-8453-8806997c5b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9df3ae2d-b741-4dc9-a624-40639976ce83-e63ab19d-37d2-4968-aaf0-26d1b86494fb&quot;)</value>
      <webElementGuid>c633379f-ce8f-47fc-9da9-9d497f1cc07f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='9df3ae2d-b741-4dc9-a624-40639976ce83-e63ab19d-37d2-4968-aaf0-26d1b86494fb']</value>
      <webElementGuid>b300bc7e-a2a8-4bec-83da-7f2bf961b871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='8fc05f62-1c73-47f7-b1d8-a3ca8d971bcd']/li[3]</value>
      <webElementGuid>144ca2c4-3386-4b4b-8069-c64852fe216b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logistic'])[1]/following::li[1]</value>
      <webElementGuid>8bbfd694-767f-4caf-b918-214d8ace2642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inspection'])[1]/following::li[2]</value>
      <webElementGuid>9e2901bd-b7e7-48f1-b251-1ac780fdd8d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operation'])[1]/preceding::li[1]</value>
      <webElementGuid>23e7576b-22d7-4c72-b640-ca295ea16800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project'])[1]/preceding::li[2]</value>
      <webElementGuid>e120c336-6bda-4015-81a4-62ce453ed092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Maintenance']/parent::*</value>
      <webElementGuid>f678c010-0262-4cd5-b317-95e6bd1c7212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li[3]</value>
      <webElementGuid>d8b6b7c6-cbde-49f6-86dd-032698d1f947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '9df3ae2d-b741-4dc9-a624-40639976ce83-e63ab19d-37d2-4968-aaf0-26d1b86494fb' and (text() = 'Maintenance' or . = 'Maintenance')]</value>
      <webElementGuid>b3e79697-682b-46ca-83d6-40c952605f6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
