<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Piping</name>
   <tag></tag>
   <elementGuidId>4d449b2a-aefc-4c07-a2a5-0ac732e58100</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#option-b140f077-b9d6-4812-ba99-3c4f2c75b88d-d11129bd-7aaf-412e-9b94-ef5ef43d2992</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[text()='Piping']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d7667d95-7025-4f3a-b6c5-70fe76b14373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>865e6364-3a6c-431e-9ed0-f33c6f447508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-selected ng-star-inserted</value>
      <webElementGuid>415cfc78-4fcd-451c-af9d-5f6915143376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option-b140f077-b9d6-4812-ba99-3c4f2c75b88d-d11129bd-7aaf-412e-9b94-ef5ef43d2992</value>
      <webElementGuid>7cda3bbe-4644-450d-aa00-807da0929881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>30570b74-423e-498e-a2ec-a27d0a8ce4fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>a67ba1ef-d86c-419e-96e8-3e2436e48a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Piping</value>
      <webElementGuid>20ecc8a0-73ee-46a8-95c6-98c9414762d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;option-b140f077-b9d6-4812-ba99-3c4f2c75b88d-d11129bd-7aaf-412e-9b94-ef5ef43d2992&quot;)</value>
      <webElementGuid>24a0e982-5fc8-4384-b9fc-3268d307d26e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='option-b140f077-b9d6-4812-ba99-3c4f2c75b88d-d11129bd-7aaf-412e-9b94-ef5ef43d2992']</value>
      <webElementGuid>8adced43-c735-4e6d-9e66-c50b6eb7ad34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='e6d7aea6-24a1-4679-97d0-167712f2f68a']/li[8]</value>
      <webElementGuid>cbec77a1-f8ad-481e-b74d-d1291e49cd77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pipeline'])[1]/following::li[1]</value>
      <webElementGuid>c66eb73f-060d-485d-ba8e-893f37832050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operation/Process'])[1]/following::li[2]</value>
      <webElementGuid>69cf2214-dac4-4777-bb2c-e74a1fbcccfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project'])[1]/preceding::li[1]</value>
      <webElementGuid>8ca7a1c4-3478-4a02-b71b-3da1fada64f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rotating'])[1]/preceding::li[2]</value>
      <webElementGuid>849ca05d-f810-4485-9f09-37813a6517de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Piping']/parent::*</value>
      <webElementGuid>7b863ca5-8d1a-467d-8376-d173bf400bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]</value>
      <webElementGuid>71058797-ad06-4d61-a067-c1e8586e786f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'option-b140f077-b9d6-4812-ba99-3c4f2c75b88d-d11129bd-7aaf-412e-9b94-ef5ef43d2992' and (text() = 'Piping' or . = 'Piping')]</value>
      <webElementGuid>90edc3d7-e5db-4b32-a6bd-38b736c93ecc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
