<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Pre Execution</name>
   <tag></tag>
   <elementGuidId>904a3337-d218-4fcd-bfb8-76eec3309d84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#option-ba7d7204-b528-4907-8b52-9f6c7ac9e700-2002e36d-45bb-4971-b9f8-f30c613fc65d</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[text()='Pre Execution']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>9b563970-9586-47c3-b7f0-20b001cf248a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c7b553d3-8671-4885-a80a-4a405a525e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-selected ng-star-inserted</value>
      <webElementGuid>b847e8b4-9621-46d9-b420-c5518b10bb1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option-ba7d7204-b528-4907-8b52-9f6c7ac9e700-2002e36d-45bb-4971-b9f8-f30c613fc65d</value>
      <webElementGuid>867d031a-97af-4908-9373-bb065b71bc62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>fcd53a04-a8cb-498f-a3fb-2d3b887c02a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c4991f68-dadb-41ac-9eab-c141c957d32a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pre Execution</value>
      <webElementGuid>ab10877b-1496-481e-b537-31d004ef42c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;option-ba7d7204-b528-4907-8b52-9f6c7ac9e700-2002e36d-45bb-4971-b9f8-f30c613fc65d&quot;)</value>
      <webElementGuid>28091e85-ac01-4e76-a58c-cf853f226ccb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='option-ba7d7204-b528-4907-8b52-9f6c7ac9e700-2002e36d-45bb-4971-b9f8-f30c613fc65d']</value>
      <webElementGuid>20368087-96e3-4725-beb6-14246affd439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='cf9547ed-8b8e-42bf-8e52-338daca6b6f4']/li</value>
      <webElementGuid>7f2121f2-1b45-4d03-b3b4-41ddb8f1b184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/following::li[2]</value>
      <webElementGuid>ef940f5c-9aa7-4742-a9d3-cde720560a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='items per page'])[1]/following::li[2]</value>
      <webElementGuid>b1d91bc7-4784-4142-aacc-23b74de72d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shutdown'])[1]/preceding::li[1]</value>
      <webElementGuid>f5cdf491-3130-4b63-9cbb-20693403e123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Execution'])[1]/preceding::li[2]</value>
      <webElementGuid>b2e7f67f-985d-47a0-8a48-fd9c16083101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pre Execution']/parent::*</value>
      <webElementGuid>d8619433-a90d-49dc-8483-a9e1f1f06e84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kendo-list/div/ul/li</value>
      <webElementGuid>6440438d-893a-4993-a4c0-11f10b6c4352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'option-ba7d7204-b528-4907-8b52-9f6c7ac9e700-2002e36d-45bb-4971-b9f8-f30c613fc65d' and (text() = 'Pre Execution' or . = 'Pre Execution')]</value>
      <webElementGuid>59301c03-c112-476d-a186-c288a107f51e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
