<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_PETRONAS Penapisan Terengganu Sdn Bhd</name>
   <tag></tag>
   <elementGuidId>3ac2dd14-8ce8-4690-a30f-08b4358bec13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[text()='PETRONAS Penapisan Terengganu Sdn Bhd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a0954a00-6a56-4aa5-9409-ecfce9da6b42-bd0b194c-847f-4921-8e7c-85019c908f44</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>aa1461f2-6961-42a0-a2ef-b00a02a37119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>437ab683-c78c-47fe-a0c4-cab67855ac9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>f08ecfc8-c3b2-462a-a283-e0c5f103a4d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a0954a00-6a56-4aa5-9409-ecfce9da6b42-bd0b194c-847f-4921-8e7c-85019c908f44</value>
      <webElementGuid>2f171ffb-a1cb-488e-ad5d-2523f8cf383b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>909b1c8d-56a0-421f-8862-8f18c517e376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>9c626065-d97f-4f58-8e20-e5c8ba081ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PETRONAS Penapisan Terengganu Sdn Bhd</value>
      <webElementGuid>a4d4741d-a7bd-4598-900d-d51da6bfc20b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a0954a00-6a56-4aa5-9409-ecfce9da6b42-bd0b194c-847f-4921-8e7c-85019c908f44&quot;)</value>
      <webElementGuid>2c28586d-d621-4f49-a62a-cffa90c19254</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='a0954a00-6a56-4aa5-9409-ecfce9da6b42-bd0b194c-847f-4921-8e7c-85019c908f44']</value>
      <webElementGuid>3cb9bc22-f28b-462e-ab30-5b14d643780d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='7ed94459-c521-4620-b990-909f1260571d']/li[10]</value>
      <webElementGuid>925a9def-4aaf-486f-9ffc-d29d9853b73d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PETRONAS Gas Berhad'])[1]/following::li[1]</value>
      <webElementGuid>7f75c600-0dd1-4443-9bb1-5029c019ade8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PETRONAS Carigali Sarawak Asset'])[1]/following::li[2]</value>
      <webElementGuid>e9910721-b2f5-41e3-9b14-3990e731c467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Okay'])[1]/preceding::li[1]</value>
      <webElementGuid>dbaff6d6-46f2-457f-952d-bb3856a46d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PETRONAS Penapisan Terengganu Sdn Bhd']/parent::*</value>
      <webElementGuid>7a829f44-c21f-47fa-9b29-d344e9585bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]</value>
      <webElementGuid>28833815-6cef-4b95-baee-096c71a93001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'a0954a00-6a56-4aa5-9409-ecfce9da6b42-bd0b194c-847f-4921-8e7c-85019c908f44' and (text() = 'PETRONAS Penapisan Terengganu Sdn Bhd' or . = 'PETRONAS Penapisan Terengganu Sdn Bhd')]</value>
      <webElementGuid>af94f7af-394f-4ec3-827a-ddb71fc3decf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
