<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_PC Ammonia Sdn Bhd</name>
   <tag></tag>
   <elementGuidId>c67c4d9f-271b-4638-bd18-ada344aee86a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='89bbaa64-cb36-42aa-b8f2-bbee63a39912-e3c7e181-44c6-4054-e7e8-08dcedae53ed']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#89bbaa64-cb36-42aa-b8f2-bbee63a39912-e3c7e181-44c6-4054-e7e8-08dcedae53ed</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>bcb2d794-017f-4f44-b9f2-10b7082cfec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>2813ec06-d0f0-4598-81a2-e0ccb789c2a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>5a33b45d-fca2-4c00-98de-c352a9ccb807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>89bbaa64-cb36-42aa-b8f2-bbee63a39912-e3c7e181-44c6-4054-e7e8-08dcedae53ed</value>
      <webElementGuid>84ae5b4e-d73d-4dc6-9791-37b3f788759d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e0a25190-e3d0-4051-be8e-1ca526a10cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>2a73f565-0ee0-473a-848d-bca597021278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PC Ammonia Sdn Bhd</value>
      <webElementGuid>330cec57-0612-47d4-b47a-8b6292c4dcc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;89bbaa64-cb36-42aa-b8f2-bbee63a39912-e3c7e181-44c6-4054-e7e8-08dcedae53ed&quot;)</value>
      <webElementGuid>bb365a4c-9bb3-49d7-ba4a-fe3913e62565</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='89bbaa64-cb36-42aa-b8f2-bbee63a39912-e3c7e181-44c6-4054-e7e8-08dcedae53ed']</value>
      <webElementGuid>cc9968c3-fbbc-4388-989d-c94b94bf79cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='36cd5ad0-65cd-45d1-a3f8-9a91bf1ff83e']/li[4]</value>
      <webElementGuid>7a4ba7fc-4c88-42b9-9962-102243729df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Malaysian Refining Company Sdn Bhd'])[1]/following::li[1]</value>
      <webElementGuid>ed160a8a-66af-4cbc-a01e-ff8f065b1187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Malaysia LNG Sdn Bhd'])[1]/following::li[2]</value>
      <webElementGuid>e9536056-a19b-4a47-b694-a00cb7d512de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PCGB PC INA'])[1]/preceding::li[1]</value>
      <webElementGuid>095e3106-8082-4d38-a032-f0f486bf81c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PCGB PCMSB Plant 1'])[1]/preceding::li[2]</value>
      <webElementGuid>3b0b651f-1813-4e19-8d77-54927114d6db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PC Ammonia Sdn Bhd']/parent::*</value>
      <webElementGuid>b7012c32-fe79-4464-bfaa-8df0d220b1ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]</value>
      <webElementGuid>9c2818ed-e3bb-4ffe-85c4-96bd30888f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '89bbaa64-cb36-42aa-b8f2-bbee63a39912-e3c7e181-44c6-4054-e7e8-08dcedae53ed' and (text() = 'PC Ammonia Sdn Bhd' or . = 'PC Ammonia Sdn Bhd')]</value>
      <webElementGuid>9ae6ba18-a849-4e52-8c69-77d775adec77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
