<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Post Execution</name>
   <tag></tag>
   <elementGuidId>8047bd62-d863-460b-86d9-6c15e3e1a478</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#option-ba7d7204-b528-4907-8b52-9f6c7ac9e700-41df4b57-f13d-4bd9-81a3-fca86433c513</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[text()='Post Execution']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>decf1d2f-9550-4efb-a320-990c1efdab9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>a23e24d7-13c7-425e-abfc-4b60457e5a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-selected ng-star-inserted</value>
      <webElementGuid>f6e54d6c-2ab7-4d5a-ba17-68ec94d2794a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option-ba7d7204-b528-4907-8b52-9f6c7ac9e700-41df4b57-f13d-4bd9-81a3-fca86433c513</value>
      <webElementGuid>45e7157b-8724-48fe-b0b4-01a29bdb3b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>77d54a4b-6e22-43e3-8392-bab6be0df847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>391d29a3-8e14-4b67-b876-dd5d146ccb7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Post Execution</value>
      <webElementGuid>17e0de0e-af89-4ab1-b02a-96e51b0e7fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;option-ba7d7204-b528-4907-8b52-9f6c7ac9e700-41df4b57-f13d-4bd9-81a3-fca86433c513&quot;)</value>
      <webElementGuid>2c8886a5-e851-46dd-b4be-1d2a70425555</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='option-ba7d7204-b528-4907-8b52-9f6c7ac9e700-41df4b57-f13d-4bd9-81a3-fca86433c513']</value>
      <webElementGuid>50fc17a5-9a02-42f8-84e1-99d2a43ee5d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='cf9547ed-8b8e-42bf-8e52-338daca6b6f4']/li[5]</value>
      <webElementGuid>259577e9-95bf-49cf-b04d-ff725a1fa876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Up'])[1]/following::li[1]</value>
      <webElementGuid>b1b03cd4-22ee-49b3-ae0b-b21f02c85060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Execution'])[1]/following::li[2]</value>
      <webElementGuid>bdfad228-102a-4bcc-aced-e01c3253389b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Okay'])[1]/preceding::li[1]</value>
      <webElementGuid>7f3dd140-289f-47e4-bd0f-33f0ae2432eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EWRApproveExecution'])[3]/preceding::li[1]</value>
      <webElementGuid>9d5e7b8e-6bf0-4524-860a-dc9b94b62d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Post Execution']/parent::*</value>
      <webElementGuid>e1231d6a-fb4a-4f11-b76d-bc157cc182ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]</value>
      <webElementGuid>242ae3dd-8128-404d-b44a-786443a88dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'option-ba7d7204-b528-4907-8b52-9f6c7ac9e700-41df4b57-f13d-4bd9-81a3-fca86433c513' and (text() = 'Post Execution' or . = 'Post Execution')]</value>
      <webElementGuid>17c509a3-9cd3-476c-8d69-945f2e00e6e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
