<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Static (1)</name>
   <tag></tag>
   <elementGuidId>b2f06402-3b99-4ee0-93c9-30d779702d51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[text()='Static']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#d0440352-85c3-4b4a-9c50-248d46cb94da-f8ae7d7e-4743-4176-a8bc-bf55bbe619e8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>72c89e3c-644b-4bef-88c7-d8be26c08f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c71c6a2a-185b-4e63-a8c3-05b550e91da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted</value>
      <webElementGuid>2a5a9034-962f-49c5-816a-8ca94af16c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>d0440352-85c3-4b4a-9c50-248d46cb94da-f8ae7d7e-4743-4176-a8bc-bf55bbe619e8</value>
      <webElementGuid>e03a02d4-d752-4d49-86fb-d315028bd2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>fc43a380-9d2c-47d1-b2ea-b4d97a9cc32e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>861cf555-e2e3-47fa-a0ed-86ee0dda071d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Static</value>
      <webElementGuid>9c58f4c4-ccb0-42dd-b0b0-31bada752a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d0440352-85c3-4b4a-9c50-248d46cb94da-f8ae7d7e-4743-4176-a8bc-bf55bbe619e8&quot;)</value>
      <webElementGuid>2533ce05-3613-4f7f-9049-870e73f822b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='d0440352-85c3-4b4a-9c50-248d46cb94da-f8ae7d7e-4743-4176-a8bc-bf55bbe619e8']</value>
      <webElementGuid>59d8ada1-63c6-4ea6-9f16-9f072384ee10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='b7f02961-5e86-457c-bc1d-2c1ee4f0eb8b']/li[11]</value>
      <webElementGuid>a2a03730-79c3-4e83-985b-b7c28b303fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rotating'])[1]/following::li[1]</value>
      <webElementGuid>cbeb30e4-a1fd-42aa-94c0-87087e684a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project'])[1]/following::li[2]</value>
      <webElementGuid>757d9ef1-47b3-4001-8a1e-9206f8117d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Okay'])[1]/preceding::li[1]</value>
      <webElementGuid>75950d03-f4d5-4b9b-87b0-65f1a2e03890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Static']/parent::*</value>
      <webElementGuid>cd46de06-9c8c-4b9f-a0d7-95ef2a34d4d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]</value>
      <webElementGuid>d5c4c877-049b-4609-839e-d70ae35963b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'd0440352-85c3-4b4a-9c50-248d46cb94da-f8ae7d7e-4743-4176-a8bc-bf55bbe619e8' and (text() = 'Static' or . = 'Static')]</value>
      <webElementGuid>619ffedc-beab-48be-a51d-65bd832d2d96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
