<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Start Up</name>
   <tag></tag>
   <elementGuidId>0d93be83-c7fa-48f0-b426-4b208683d629</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#option-ba7d7204-b528-4907-8b52-9f6c7ac9e700-983e1aef-e837-4a55-a3ba-2e84b0117471</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[text()='Start Up']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>1856044b-4c2b-4d79-bbfd-72774e3bb430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>4578f7e2-f1ed-461d-b6aa-cd7468ced2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-selected ng-star-inserted</value>
      <webElementGuid>db8ad9e6-3f27-4d00-a1ab-ca2777db367e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option-ba7d7204-b528-4907-8b52-9f6c7ac9e700-983e1aef-e837-4a55-a3ba-2e84b0117471</value>
      <webElementGuid>665930b3-e94e-4783-a26d-c9573ef799dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>fafde36e-8a41-4241-8176-10a980fd6bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>b490177c-b4e5-421f-842e-2c5339f24e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start Up</value>
      <webElementGuid>de064805-da2a-4a7a-afcb-ee0397853000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;option-ba7d7204-b528-4907-8b52-9f6c7ac9e700-983e1aef-e837-4a55-a3ba-2e84b0117471&quot;)</value>
      <webElementGuid>a27e616e-33d0-4fdf-864f-b405d48c581a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='option-ba7d7204-b528-4907-8b52-9f6c7ac9e700-983e1aef-e837-4a55-a3ba-2e84b0117471']</value>
      <webElementGuid>d48a9b56-172e-4346-8bc3-dbad8db904fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='cf9547ed-8b8e-42bf-8e52-338daca6b6f4']/li[4]</value>
      <webElementGuid>3a69932d-bd38-4b94-9b86-6eb6c023c0c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Execution'])[1]/following::li[1]</value>
      <webElementGuid>03d1d867-c298-4b86-b4a8-02418d492acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shutdown'])[1]/following::li[2]</value>
      <webElementGuid>9eb0babe-2ec4-47c6-85fd-cd041a0837d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post Execution'])[1]/preceding::li[1]</value>
      <webElementGuid>d6b3f9fa-39ea-4a41-8039-bee9f19d1143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Okay'])[1]/preceding::li[2]</value>
      <webElementGuid>84ee070d-c2ca-4154-be4d-a12e96eeb23e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Start Up']/parent::*</value>
      <webElementGuid>a0f56085-f0f3-4359-a1cc-7d88497273de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]</value>
      <webElementGuid>60ec4dc9-5cd0-42e6-b1bb-b96127b01d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'option-ba7d7204-b528-4907-8b52-9f6c7ac9e700-983e1aef-e837-4a55-a3ba-2e84b0117471' and (text() = 'Start Up' or . = 'Start Up')]</value>
      <webElementGuid>01760ac7-abe9-42c7-a473-691828b32be5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
