<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Static</name>
   <tag></tag>
   <elementGuidId>9e5890ec-79ae-4368-adc8-e9801561d9c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#option-b140f077-b9d6-4812-ba99-3c4f2c75b88d-f8ae7d7e-4743-4176-a8bc-bf55bbe619e8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[text()='Static']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>309dc2a3-8d31-4083-87d7-6af6cc659d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>01904f28-f416-4cec-8b56-c3bff05749bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-selected ng-star-inserted</value>
      <webElementGuid>fbb20575-0fce-4580-984d-4ecceb098956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option-b140f077-b9d6-4812-ba99-3c4f2c75b88d-f8ae7d7e-4743-4176-a8bc-bf55bbe619e8</value>
      <webElementGuid>61ef7ac1-12b9-4736-9a76-1d396f6aeb94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8d7c2bb5-410a-4f37-b908-746be6a6855e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>438170c8-508d-48bd-8399-a692ad18bf10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Static</value>
      <webElementGuid>4c27bf1d-1d17-456e-9881-9dd11e2e564e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;option-b140f077-b9d6-4812-ba99-3c4f2c75b88d-f8ae7d7e-4743-4176-a8bc-bf55bbe619e8&quot;)</value>
      <webElementGuid>1cca662d-0744-47ff-9362-7b02d293af04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='option-b140f077-b9d6-4812-ba99-3c4f2c75b88d-f8ae7d7e-4743-4176-a8bc-bf55bbe619e8']</value>
      <webElementGuid>21716ab8-6636-4272-901d-69c7038c9490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='e6d7aea6-24a1-4679-97d0-167712f2f68a']/li[11]</value>
      <webElementGuid>d2da01fd-e609-48bd-9413-06c334b721eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rotating'])[1]/following::li[1]</value>
      <webElementGuid>90b7ec4a-25ec-43cc-b59d-dd30e02a5eb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project'])[1]/following::li[2]</value>
      <webElementGuid>0a48cf1a-b55a-4ae8-be6f-8bbf53b71194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Okay'])[1]/preceding::li[1]</value>
      <webElementGuid>e7f9db37-3285-4685-9a2a-7d1f1ba9ea81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EWRApproveExecution'])[3]/preceding::li[1]</value>
      <webElementGuid>da1c540f-b7d8-443f-8491-8eecc0a2f26b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Static']/parent::*</value>
      <webElementGuid>003948fb-62ca-4891-ad24-f3292564d547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]</value>
      <webElementGuid>26d03693-314f-4cc8-8f77-4ad3d16bc64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'option-b140f077-b9d6-4812-ba99-3c4f2c75b88d-f8ae7d7e-4743-4176-a8bc-bf55bbe619e8' and (text() = 'Static' or . = 'Static')]</value>
      <webElementGuid>c2dc7afc-e027-4072-b0e5-168cbe05dc97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
