<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_tupdater1pethlab.com</name>
   <tag></tag>
   <elementGuidId>07cd703b-9ccb-4f08-a400-609c1678f031</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='11dbe30b-b8f3-4c90-9f5a-1a47783cb10b-tupdater1@pethlab.com']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8ea53736-e068-47b9-8b20-6ec1465424db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>77cedd4d-651a-4f83-9241-5d429a4cdd1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item ng-star-inserted k-state-focused</value>
      <webElementGuid>e3cd849f-36d2-4f5d-ade6-16b0457e642e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>11dbe30b-b8f3-4c90-9f5a-1a47783cb10b-tupdater1@pethlab.com</value>
      <webElementGuid>dca42e03-200c-4542-9702-c42acf9c9e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>02142022-c4d3-4e31-a5c2-a5a8e1a24010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bd084ed3-3c05-4403-a875-21003033d1ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>tupdater1@pethlab.com</value>
      <webElementGuid>c11a6d59-cd90-4214-a6c1-afb109724564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;11dbe30b-b8f3-4c90-9f5a-1a47783cb10b-tupdater1@pethlab.com&quot;)</value>
      <webElementGuid>20332f6b-05ac-4a23-824b-fa6caca83bc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='11dbe30b-b8f3-4c90-9f5a-1a47783cb10b-tupdater1@pethlab.com']</value>
      <webElementGuid>b1c5d933-3820-4cb9-920a-d223d25f728c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='9ea57905-080b-49db-9203-4a0ae56eabf5']/li</value>
      <webElementGuid>7dbbf55b-f721-4034-964c-50c84c31f7bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::li[1]</value>
      <webElementGuid>5c8beaab-98d6-41de-8b12-ca8c0111a3fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::li[1]</value>
      <webElementGuid>a4fda21a-6896-4649-9086-c3e9a8a1390d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tupdater10@pethlab.com'])[1]/preceding::li[1]</value>
      <webElementGuid>772897ee-b135-4eae-975e-75bf38fe1302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='updater1@pethlab.com'])[1]/preceding::li[2]</value>
      <webElementGuid>ff82cf95-69f7-4814-93e1-6bb7ce768ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='tupdater1@pethlab.com']/parent::*</value>
      <webElementGuid>8f5d03a9-bab1-46c2-b514-1e44f1f28af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kendo-list/div/ul/li</value>
      <webElementGuid>9fc013cc-dc9d-441e-8ece-ed82863601bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '11dbe30b-b8f3-4c90-9f5a-1a47783cb10b-tupdater1@pethlab.com' and (text() = 'tupdater1@pethlab.com' or . = 'tupdater1@pethlab.com')]</value>
      <webElementGuid>6ca89ced-3371-4a8f-a15a-afbe108d06e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
