<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Demo - Training  MNLG - Demo TP  Dem_be5ca4</name>
   <tag></tag>
   <elementGuidId>29f549f1-9662-430d-9f69-73f6dcf798ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#event-list</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='event-list']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f8c2541c-4a55-44af-848b-a625fb5d5bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>event-list</value>
      <webElementGuid>2095d740-a644-4d47-8118-f1c241c6aca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Demo - Training  MNLG - Demo TP  Demo-Nayli  DEMO_SN  MRCSB-TP-2025  EVENT - REGRESSION  EVENT - REGRESSION 2  REGRESSION - LOC  TCBODS-01 </value>
      <webElementGuid>3ab4c7cf-968d-4da6-bbe5-f1d9d7c19cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;event-list&quot;)</value>
      <webElementGuid>8cec8fd3-0c56-4ffd-81dc-d6cfb872a00e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='event-list']</value>
      <webElementGuid>d72fd7a2-598b-40a8-b74f-c7043b41c6fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/following::select[1]</value>
      <webElementGuid>5cc655a3-d42f-4c8c-b386-971f99abaf92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPU'])[1]/following::select[2]</value>
      <webElementGuid>7099a5a9-2e5e-41fc-83ff-def196561574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Execution Homepage'])[1]/preceding::select[1]</value>
      <webElementGuid>ceff9f7d-e3bf-46db-b92a-050affe82f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Notifications (0)'])[1]/preceding::select[1]</value>
      <webElementGuid>4b1a1bba-52b4-4597-b020-4f52fce6285b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/select</value>
      <webElementGuid>52e7e261-b388-420a-9ec7-3bcf4f71add1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'event-list' and (text() = ' Demo - Training  MNLG - Demo TP  Demo-Nayli  DEMO_SN  MRCSB-TP-2025  EVENT - REGRESSION  EVENT - REGRESSION 2  REGRESSION - LOC  TCBODS-01 ' or . = ' Demo - Training  MNLG - Demo TP  Demo-Nayli  DEMO_SN  MRCSB-TP-2025  EVENT - REGRESSION  EVENT - REGRESSION 2  REGRESSION - LOC  TCBODS-01 ')]</value>
      <webElementGuid>9583f0bb-effb-4ff2-95ee-bb44c7f9ef22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
