<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Demo_1</name>
   <tag></tag>
   <elementGuidId>88aa2566-3f15-47a9-9e27-4069f9f806e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cc4b2ff9-23c0-4b47-a164-f2cfbdbb93a4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cc4b2ff9-23c0-4b47-a164-f2cfbdbb93a4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bf829b7d-7512-495d-8188-c2fcc537f16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>a939c120-5913-4f8d-b5c3-87609f438100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>f315ca1e-7705-4ae8-b4ce-452170c34507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cc4b2ff9-23c0-4b47-a164-f2cfbdbb93a4</value>
      <webElementGuid>cc69d473-ae3e-4d54-83fb-9408c879919f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Demo</value>
      <webElementGuid>58af0e9c-7e96-41aa-8390-73765d664c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cc4b2ff9-23c0-4b47-a164-f2cfbdbb93a4&quot;)</value>
      <webElementGuid>09c316a9-23fa-478a-a205-bb5809c7529a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='cc4b2ff9-23c0-4b47-a164-f2cfbdbb93a4']</value>
      <webElementGuid>ccb73c36-e6b8-462d-ba8a-69ae9ee1cfba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-9d9d84f7-90d3-4c6f-8c83-3083dc27ca86']/span</value>
      <webElementGuid>84f26f9c-46c9-4341-8e49-2e20c5058ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPU'])[1]/following::span[2]</value>
      <webElementGuid>023b6f40-becd-4492-8bce-1c2493fce748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role Management'])[3]/following::span[2]</value>
      <webElementGuid>d59c5b66-b082-48ba-a9a8-6cdf696337b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/preceding::span[3]</value>
      <webElementGuid>29e1879e-e19d-45c9-8ed5-9f1dcab23620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Testing'])[1]/preceding::span[3]</value>
      <webElementGuid>10d0a9bf-50f4-4f55-b9c7-67fdfdebbb1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Demo']/parent::*</value>
      <webElementGuid>d2169d31-df47-4cf5-9cfb-fbae0e48355e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/kendo-dropdownlist/span/span</value>
      <webElementGuid>85788ef7-23c9-41c1-9489-e5bd594f1f29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'cc4b2ff9-23c0-4b47-a164-f2cfbdbb93a4' and (text() = 'Demo' or . = 'Demo')]</value>
      <webElementGuid>eb9c41dc-93fc-4651-95d8-6801f2ff0f87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
