<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Assurance M_1</name>
   <tag></tag>
   <elementGuidId>390d66e1-b206-41c2-a5e4-8e90b07740ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='c27b152d-67cc-42c3-b56a-4494e572cd71']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c27b152d-67cc-42c3-b56a-4494e572cd71</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>04965f45-2e0c-4c83-ba1e-0c547b45b656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>a08ef026-699d-4474-add8-6ed93855cb41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>e992ef54-fbbe-4156-b7c8-32d3a2cd008f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c27b152d-67cc-42c3-b56a-4494e572cd71</value>
      <webElementGuid>f9d46b38-4319-403b-a5a7-6f6e9469ad94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Assurance M</value>
      <webElementGuid>1937bf20-b0e3-44b3-84c7-3247f6c886bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c27b152d-67cc-42c3-b56a-4494e572cd71&quot;)</value>
      <webElementGuid>6ac035a8-daf2-4790-aac0-ed5cb80b8991</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='c27b152d-67cc-42c3-b56a-4494e572cd71']</value>
      <webElementGuid>237ec153-55b0-4503-ada7-4701bf73793c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-3827f7a9-49e8-4f33-834d-682189aecb97']/span</value>
      <webElementGuid>8f85d771-ba4c-4642-b02d-ce37fdb8c9eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::span[2]</value>
      <webElementGuid>21963045-9d0b-4fdb-9c04-eb6306c4ceff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/following::span[3]</value>
      <webElementGuid>6fc3b0b1-3c5b-4ee1-a676-a1f9d0f4a30e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register Multiple User'])[1]/preceding::span[3]</value>
      <webElementGuid>83bfef8c-996d-47d8-809e-a823e45ae57d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New User'])[1]/preceding::span[4]</value>
      <webElementGuid>ca60cd86-3c95-4715-ad61-e7ce8afddef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Assurance M']/parent::*</value>
      <webElementGuid>08964ae7-59ba-471b-8671-9f7d6743f7d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/kendo-dropdownlist/span/span</value>
      <webElementGuid>f82ac779-3270-4767-a958-6bfb1d01705e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'c27b152d-67cc-42c3-b56a-4494e572cd71' and (text() = 'Assurance M' or . = 'Assurance M')]</value>
      <webElementGuid>0daa0b20-3686-4d2b-b08c-b317856607aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='8346d46b-040a-4ba4-8e3c-173c6852ce00']</value>
      <webElementGuid>0bb24427-8e1b-435a-9f64-ff0cf71dc90b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-1dde2e65-f0e3-464d-9333-fbf9cbcbf819']/span</value>
      <webElementGuid>c04967d9-572d-4cb5-8919-866d142ff3d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '8346d46b-040a-4ba4-8e3c-173c6852ce00' and (text() = 'Assurance M' or . = 'Assurance M')]</value>
      <webElementGuid>5363e345-8377-4634-9316-bc299a579f66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
