<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Demo</name>
   <tag></tag>
   <elementGuidId>777a9688-1b82-477a-a9a9-78dfbedce0c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;user-listing&quot;]/div/div[1]/div[1]/kendo-dropdownlist</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#8c5de3b4-876b-40eb-8b11-370912d33b39</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4e981daf-a71f-47bd-bf9f-0553bb970755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>e754656c-573f-447d-8694-f6fd55ae04d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>b27b71ad-3a38-4969-a615-cde7cc6bf087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>8c5de3b4-876b-40eb-8b11-370912d33b39</value>
      <webElementGuid>9e439837-5c41-4335-bc8d-2d5978463556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Demo</value>
      <webElementGuid>03b74a90-6a49-4b3a-b9f7-73790e316db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;8c5de3b4-876b-40eb-8b11-370912d33b39&quot;)</value>
      <webElementGuid>922589c0-e1bd-408a-9b2f-31ddc835c5fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='8c5de3b4-876b-40eb-8b11-370912d33b39']</value>
      <webElementGuid>8450694e-890e-4af2-84a0-33c18f6239cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-4d076aa9-52c3-4fb6-907a-0badfff9a06d']/span</value>
      <webElementGuid>578d3bfd-cb53-4d18-b13c-55bb586d6fe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPU'])[1]/following::span[2]</value>
      <webElementGuid>4da9c8ee-5692-4e32-b24a-109271c7d0b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role Management'])[3]/following::span[2]</value>
      <webElementGuid>040601de-9435-48b1-81c4-e0f9a86f2983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/preceding::span[3]</value>
      <webElementGuid>86d78760-7293-4e45-b307-c5b08da7b73d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Testing'])[1]/preceding::span[3]</value>
      <webElementGuid>0686c112-7dcd-4a49-88dc-aff109720e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Demo']/parent::*</value>
      <webElementGuid>dd8cb277-ef69-4b56-bb13-f335b21571bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/kendo-dropdownlist/span/span</value>
      <webElementGuid>05388e07-26e1-41ef-b756-4557c1c10f18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '8c5de3b4-876b-40eb-8b11-370912d33b39' and (text() = 'Demo' or . = 'Demo')]</value>
      <webElementGuid>f7d3b20b-cc58-4356-8e9a-051f520137aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='125e4732-80b0-42d0-a4ab-b8f700675026']</value>
      <webElementGuid>4956b853-9e21-4abd-81c9-1eb61d7786a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-0e0a5a4f-2d01-4092-b369-0abd06f84019']/span</value>
      <webElementGuid>9b206187-f111-4ec7-9007-2d0d43a97884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '125e4732-80b0-42d0-a4ab-b8f700675026' and (text() = 'Demo' or . = 'Demo')]</value>
      <webElementGuid>407e9321-64b0-4e50-8fdb-a9b58e65adb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='451506ce-91a1-43f7-8ebb-eaec876ce038']</value>
      <webElementGuid>45477402-f597-4115-b0c0-bc5d1c016457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-896e4ffe-aee8-4a60-8800-d61d48c0ae3b']/span</value>
      <webElementGuid>205a19f2-6c82-421a-a071-997247be67cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::span[2]</value>
      <webElementGuid>1b9c847b-edd1-4bc4-b26b-36cb5fe5949e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPU'])[1]/following::span[3]</value>
      <webElementGuid>78cca1cc-52a3-43fb-b06a-aa9976228a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::span[3]</value>
      <webElementGuid>627afe08-7e62-47dd-9526-a0f2dd0d91fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '451506ce-91a1-43f7-8ebb-eaec876ce038' and (text() = 'Demo' or . = 'Demo')]</value>
      <webElementGuid>d560d904-5243-4e7c-a346-004604974392</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
