<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sub Location 2_8e77b03c-57aa-4084-920e_7f7e63</name>
   <tag></tag>
   <elementGuidId>eaed1c16-9406-4c3d-a2d4-1c8982d01e6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='8e77b03c-57aa-4084-920e-8101bc8b88fe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#8e77b03c-57aa-4084-920e-8101bc8b88fe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>04af2eca-67c2-4b1e-a787-6b6c5022b788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>8ee70947-7d6d-433a-a7b1-ce87d6839253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>bdb02457-7e9d-4047-8f0c-16be549d1f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>8e77b03c-57aa-4084-920e-8101bc8b88fe</value>
      <webElementGuid>5003c2d4-2ff7-4c62-8bfd-9c7c65febc6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;8e77b03c-57aa-4084-920e-8101bc8b88fe&quot;)</value>
      <webElementGuid>602f848a-369e-49ad-bfa4-a4d8572538bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='8e77b03c-57aa-4084-920e-8101bc8b88fe']</value>
      <webElementGuid>be0083d4-0db7-40b8-a95c-692c3ab97adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-4e85e596-e3c1-4952-bc34-e85d421e538c']/span</value>
      <webElementGuid>a0962b50-7b38-486f-a5b7-9f306afe3b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub Location 2'])[1]/following::span[2]</value>
      <webElementGuid>a5bd61fc-7f67-4e4b-8f0e-ced4b7f77a83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GHH'])[1]/following::span[4]</value>
      <webElementGuid>31c6a2ea-ad1d-41bf-9ca3-022f75552833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Info'])[1]/preceding::span[3]</value>
      <webElementGuid>1e2e8ffa-0815-41ac-9c0e-725a1ee6f8f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/kendo-dropdownlist/span/span</value>
      <webElementGuid>916e7c1d-bd63-48c6-b70c-4dde234c459a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '8e77b03c-57aa-4084-920e-8101bc8b88fe']</value>
      <webElementGuid>768334cf-415a-4072-b4cd-254a631ebbd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
