<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select role</name>
   <tag></tag>
   <elementGuidId>8208d9d2-5e63-44e3-a8b2-94ccc4d5ddc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;project-detail&quot;]/div[2]/app-role-loc-modal/div/div/div/div[2]/div/div[1]/div[4]/kendo-dropdownlist</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acfe6375-7545-4aab-b729-dea1835e9b80</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>137c0f21-d60b-4bb8-87d5-4317b1a8dcab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>f88dd6dd-dd48-41d6-9846-bf91a0a3dc0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>33964282-cc59-4cc8-b229-e1aa1b1e2e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acfe6375-7545-4aab-b729-dea1835e9b80</value>
      <webElementGuid>dd4fccdd-aa5b-4a91-a2ff-53aa8a79691b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select role</value>
      <webElementGuid>5dc7d739-69d2-42fc-b5ea-97f4e73aa265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acfe6375-7545-4aab-b729-dea1835e9b80&quot;)</value>
      <webElementGuid>a20499ed-b11e-4fca-b8cd-7ef08670135d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='acfe6375-7545-4aab-b729-dea1835e9b80']</value>
      <webElementGuid>e73561e0-7695-4a9f-bdfe-4ff41c73df2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-9ded028a-4c47-447f-abc5-59eeae05a520']/span</value>
      <webElementGuid>3010f5f5-4639-40c0-bc8b-9d3ad5874ba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::span[2]</value>
      <webElementGuid>ace2ee1a-404a-4ae6-a1b2-67504c48fff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location Details'])[1]/preceding::span[3]</value>
      <webElementGuid>f282deb4-ff18-4c32-9b69-69e0af21b618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Location, yet.'])[1]/preceding::span[3]</value>
      <webElementGuid>3092a446-b816-4162-98f1-9e2458efa05c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select role']/parent::*</value>
      <webElementGuid>c94ca7aa-e78b-43ed-a2a4-c184c8cef8c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/kendo-dropdownlist/span/span</value>
      <webElementGuid>43eea67f-1d66-4418-b529-e4fd63029066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'acfe6375-7545-4aab-b729-dea1835e9b80' and (text() = 'Select role' or . = 'Select role')]</value>
      <webElementGuid>e40aaaca-949f-41c6-a88f-936b14315578</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
