<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Demo_Role</name>
   <tag></tag>
   <elementGuidId>88aa2566-3f15-47a9-9e27-4069f9f806e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/app-admin-layout/div[2]/div[2]/div/div/div/app-list-role/div/div/div/div/div[1]/div[1]/kendo-dropdownlist</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c94329d4-0af8-4394-854f-c5ad8cbe0a6e</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b6f32cfd-4f6d-4a14-8d4b-2c98671a0647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>96b2140e-2ef7-4d3f-b89a-2a3accdd490c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>f9426d67-b0d3-4666-98a4-6148c2ec33ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c94329d4-0af8-4394-854f-c5ad8cbe0a6e</value>
      <webElementGuid>c84a6384-78e1-4540-a9a6-fa20c83f1a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Demo</value>
      <webElementGuid>65c99a82-7152-4500-81c4-6cf920719e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c94329d4-0af8-4394-854f-c5ad8cbe0a6e&quot;)</value>
      <webElementGuid>a330e8b7-9984-4e45-b276-bcf39a83f974</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='c94329d4-0af8-4394-854f-c5ad8cbe0a6e']</value>
      <webElementGuid>ddca65b1-0593-49f7-accb-dfc49a89da86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-d04dc866-c6da-4071-b53d-639fc3d1777d']/span</value>
      <webElementGuid>0d6f2239-18d2-4061-bc98-58c6a9640c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::span[2]</value>
      <webElementGuid>a2ab36f5-b991-45c3-a475-fe50e60aaeaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPU'])[1]/following::span[3]</value>
      <webElementGuid>f66d7385-6d2a-445b-b24c-7cb0f912cfc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/preceding::span[3]</value>
      <webElementGuid>143fbf92-8e8a-4c0f-8556-dfb3fb98697f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::span[3]</value>
      <webElementGuid>6c1fc06c-b680-4534-bbd9-b7b35de9bc74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Demo']/parent::*</value>
      <webElementGuid>b4da53de-c7f9-40a1-bea8-acffa7701172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/kendo-dropdownlist/span/span</value>
      <webElementGuid>f802e317-dfa5-4bc8-8347-901ae9947d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'c94329d4-0af8-4394-854f-c5ad8cbe0a6e' and (text() = 'Demo' or . = 'Demo')]</value>
      <webElementGuid>861bf296-1847-43e6-8e13-2e28a1dc5ef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='cc4b2ff9-23c0-4b47-a164-f2cfbdbb93a4']</value>
      <webElementGuid>c001bd45-bdcb-4a70-9de7-8f8f1351d195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-9d9d84f7-90d3-4c6f-8c83-3083dc27ca86']/span</value>
      <webElementGuid>a5557cb5-7cd3-48e6-b9a7-12e4e1323080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPU'])[1]/following::span[2]</value>
      <webElementGuid>d74deab8-4001-4a16-bfaa-80cbbe613768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role Management'])[3]/following::span[2]</value>
      <webElementGuid>c52c4ae1-5ec8-4e04-8366-55c422593bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Testing'])[1]/preceding::span[3]</value>
      <webElementGuid>82a3cd35-fc9e-4f4f-8fdb-5b432dc10cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'cc4b2ff9-23c0-4b47-a164-f2cfbdbb93a4' and (text() = 'Demo' or . = 'Demo')]</value>
      <webElementGuid>1ee27d68-004e-4ce7-be95-02972213c102</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
