<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Assurance M - Role</name>
   <tag></tag>
   <elementGuidId>c7233d75-1883-4c1a-8fa7-02aa3ba6348b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/app-admin-layout/div[2]/div[2]/div/div/div/app-list-role/div/div/div/div/div[1]/div[2]/kendo-dropdownlist</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b6d3166a-10a3-4253-8ddc-b1cbac315bb8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>52502813-8793-412e-b865-56c9f5ec596f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>e5c52365-f3da-47b9-87ba-e11657bad86e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>22c9ad15-9079-4674-897d-91650b2f8e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b6d3166a-10a3-4253-8ddc-b1cbac315bb8</value>
      <webElementGuid>b1a170be-0038-4962-8bed-5ec3e93d8bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Assurance M</value>
      <webElementGuid>7daeb4bf-50d3-4ef1-9c85-0c5127ef91b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b6d3166a-10a3-4253-8ddc-b1cbac315bb8&quot;)</value>
      <webElementGuid>406242d8-3913-4db9-855d-29dc6f0987fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='b6d3166a-10a3-4253-8ddc-b1cbac315bb8']</value>
      <webElementGuid>39c15c5d-cbef-4a85-b386-2bd0d1c0713d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-113fbc90-40f0-4e3d-8048-150d90094e1a']/span</value>
      <webElementGuid>adf52610-c040-4c47-a2b6-fc4ce8d8b6e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/following::span[2]</value>
      <webElementGuid>12e841ae-6bdd-48b8-a648-765e117b43ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PETRONAS Penapisan Terengganu Sdn Bhd'])[1]/following::span[4]</value>
      <webElementGuid>72de677a-fc48-4633-9a8f-22fefca10e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[1]/preceding::span[3]</value>
      <webElementGuid>bcd3faac-9d98-4391-80db-dc5d8d3e1aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Template'])[1]/preceding::span[4]</value>
      <webElementGuid>19116330-b9dd-43e8-a26b-d5a18426f6bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Assurance M']/parent::*</value>
      <webElementGuid>07e53b37-9a4f-40a6-a7a3-add9c2e23e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/kendo-dropdownlist/span/span</value>
      <webElementGuid>ff0547e1-e01a-46a3-ace7-361ef705a8be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'b6d3166a-10a3-4253-8ddc-b1cbac315bb8' and (text() = 'Assurance M' or . = 'Assurance M')]</value>
      <webElementGuid>4be84ec6-1aa4-47cd-af44-0cfdf0b62863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='8e4c13d5-23ba-4e95-9ef5-0adeda5dbb9e']</value>
      <webElementGuid>e82a881d-cae6-4162-a3eb-efe9d18baede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-db4d932f-c964-499f-8d67-58e6d5cc42f6']/span</value>
      <webElementGuid>b00e1ab8-1f17-467d-9a13-4e9546339cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '8e4c13d5-23ba-4e95-9ef5-0adeda5dbb9e' and (text() = 'Assurance M' or . = 'Assurance M')]</value>
      <webElementGuid>483f5849-c4cf-4c01-85e5-6c2c6fcc077a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
