<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Assurance M</name>
   <tag></tag>
   <elementGuidId>7985285a-ddac-4b98-9443-0d93b4369f03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;user-listing&quot;]/div/div[1]/div[2]/kendo-dropdownlist</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#8e4c13d5-23ba-4e95-9ef5-0adeda5dbb9e</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b8273ef9-20ad-405d-aeea-0205aadb8f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>70001baf-8a63-4f2f-9b3b-b25f5db29a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>b1a38949-c101-497b-aabc-21d91044ec49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>8e4c13d5-23ba-4e95-9ef5-0adeda5dbb9e</value>
      <webElementGuid>a650d85e-f01a-4da7-8cb9-462f67864e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Assurance M</value>
      <webElementGuid>615f3ceb-e431-4281-9ab6-f45ac3780c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;8e4c13d5-23ba-4e95-9ef5-0adeda5dbb9e&quot;)</value>
      <webElementGuid>26e7775c-75a9-4198-8460-24ed55e7aea9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='8e4c13d5-23ba-4e95-9ef5-0adeda5dbb9e']</value>
      <webElementGuid>73067428-8876-47f5-ad45-1a5afe581886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-db4d932f-c964-499f-8d67-58e6d5cc42f6']/span</value>
      <webElementGuid>8fe4d3ae-fc50-4e61-8283-a86b0ffe7c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/following::span[2]</value>
      <webElementGuid>339599d2-6778-490f-b5f8-fff5bc72e294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PETRONAS Penapisan Terengganu Sdn Bhd'])[1]/following::span[4]</value>
      <webElementGuid>18264de5-b34e-4f6a-8ece-9e3281b269e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[1]/preceding::span[3]</value>
      <webElementGuid>9e73dfb8-56ee-4f8e-a34c-02858a70ce07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Template'])[1]/preceding::span[4]</value>
      <webElementGuid>c1a80821-1034-434e-91de-465a5ccf4986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Assurance M']/parent::*</value>
      <webElementGuid>49250ffd-6df1-4c6f-baa7-b20dfb99a8c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/kendo-dropdownlist/span/span</value>
      <webElementGuid>c7852281-2952-4f44-b089-6de5800800ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '8e4c13d5-23ba-4e95-9ef5-0adeda5dbb9e' and (text() = 'Assurance M' or . = 'Assurance M')]</value>
      <webElementGuid>685323ab-1c22-49ad-88b3-730cfb6d4021</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
