<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__Location1</name>
   <tag></tag>
   <elementGuidId>bbf95a90-7ab6-453a-bd7b-021d94cd598a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='work-location']//kendo-dropdownlist)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b1c9c3b6-dddd-44ce-858d-6013a8c1f13c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ccce967b-381d-4ae4-a806-1bd5e2a624e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>2aa1124c-2231-4f8f-a4ef-36290fda4e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>63c4d53c-0ea0-4e6f-bb3f-75847518e475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b1c9c3b6-dddd-44ce-858d-6013a8c1f13c</value>
      <webElementGuid>549dc570-2f66-4156-b517-761041b77987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1c9c3b6-dddd-44ce-858d-6013a8c1f13c&quot;)</value>
      <webElementGuid>c3f3e2bf-4f92-4004-bcdc-ddf052a8eef8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='b1c9c3b6-dddd-44ce-858d-6013a8c1f13c']</value>
      <webElementGuid>b667d1c3-458e-43b7-90c7-537ae5a33a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-fd93c971-2749-4505-9967-23382980ff35']/span</value>
      <webElementGuid>a93fd0f7-82ae-4b6a-8954-65bf0ad6b158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::span[2]</value>
      <webElementGuid>7293a157-ada2-4f1f-8d34-98b069cc0ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub Location 2'])[1]/preceding::span[3]</value>
      <webElementGuid>ecc38b86-f98e-4f57-9e18-f16a90c6e2a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Info'])[1]/preceding::span[7]</value>
      <webElementGuid>ed71ebb7-2109-402d-85bb-a80ccab46430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/kendo-dropdownlist/span/span</value>
      <webElementGuid>9a6a6f33-22c8-45d7-bd7f-b2754521cf20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'b1c9c3b6-dddd-44ce-858d-6013a8c1f13c']</value>
      <webElementGuid>508d8e3d-4acc-4eff-b03d-d978223e272e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
