<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__02ec40da-9caa-40a5-bfc8-8ad3c06ea692</name>
   <tag></tag>
   <elementGuidId>47a518c0-5f76-4c6b-8c4a-598d68cd95b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='work-information']//kendo-dropdownlist</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#02ec40da-9caa-40a5-bfc8-8ad3c06ea692</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7d8198f3-831f-4bf0-912a-eb1a9a5afb71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>f1d5595f-c0d6-4673-8508-44ac4f6abed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>10d4fade-06f2-4d72-9a21-63c1a11a7a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>02ec40da-9caa-40a5-bfc8-8ad3c06ea692</value>
      <webElementGuid>314c19a5-9c8f-4e70-ac3b-9b7b7df9e221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;02ec40da-9caa-40a5-bfc8-8ad3c06ea692&quot;)</value>
      <webElementGuid>0c3d549a-5495-44e7-a541-bd237b3508ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='02ec40da-9caa-40a5-bfc8-8ad3c06ea692']</value>
      <webElementGuid>e32994a0-5730-42b0-8b1e-e553de6c28db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-b009b3cb-c0cf-46e8-94b4-9a5df8b3c9ff']/span</value>
      <webElementGuid>e63a70e0-68f2-4d28-860b-66af9270680e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::span[2]</value>
      <webElementGuid>738696b7-48aa-4021-a18e-bd53f732782e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::span[3]</value>
      <webElementGuid>22ed4474-5958-4932-a659-9a40d6cef437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-work-information/div/div/div/div[2]/div/div/kendo-dropdownlist/span/span</value>
      <webElementGuid>6c7a4eb2-97c3-422d-a74c-b489cd8083c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '02ec40da-9caa-40a5-bfc8-8ad3c06ea692']</value>
      <webElementGuid>96a18b39-0f5a-4757-8065-00beaba7ba56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
