<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Demo - Execution</name>
   <tag></tag>
   <elementGuidId>4ccc1665-0c8e-4f65-970c-6b3ceeb7f47b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='52f840d1-a780-41ce-8291-7306baf29f9c']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#52f840d1-a780-41ce-8291-7306baf29f9c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ca901b40-1e3b-44db-97f3-0fcb391f7c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>41e3ee99-c118-4aa8-8009-5fc8f8d29c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>6807b080-f358-4446-b5fd-671ca69110bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>52f840d1-a780-41ce-8291-7306baf29f9c</value>
      <webElementGuid>08ca9759-2b03-4852-b988-016ddcf20612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Demo - Execution</value>
      <webElementGuid>54655210-34e7-44bc-bf28-f1c8ea96cdd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;52f840d1-a780-41ce-8291-7306baf29f9c&quot;)</value>
      <webElementGuid>e36678e6-9bdd-4abf-bce3-a4c2a185bce0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='52f840d1-a780-41ce-8291-7306baf29f9c']</value>
      <webElementGuid>1a31e130-b2f3-424b-b083-0b5457cb7917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-a12a4374-7c9c-4212-b99d-aa179dcdf6a1']/span</value>
      <webElementGuid>13346363-ae0d-4781-80d6-d9cd40213333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/following::span[2]</value>
      <webElementGuid>915c4ebc-42b6-452c-9b1a-aefe733d1b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Malaysia LNG Sdn Bhd'])[1]/following::span[4]</value>
      <webElementGuid>1583fce4-b439-43f8-acbb-98974a417f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[1]/preceding::span[3]</value>
      <webElementGuid>e9753863-1af7-43c7-a91d-0d0bbf4fc279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Template'])[1]/preceding::span[4]</value>
      <webElementGuid>cf1c8fe6-0be2-4b7a-a40d-0c1ccc2fc5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Demo - Execution']/parent::*</value>
      <webElementGuid>defd74a5-148b-4ee1-bd4a-9a7e615313ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/kendo-dropdownlist/span/span</value>
      <webElementGuid>6d7a2857-8404-4eb8-ad52-6b36ac73291a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '52f840d1-a780-41ce-8291-7306baf29f9c' and (text() = 'Demo - Execution' or . = 'Demo - Execution')]</value>
      <webElementGuid>c3f582a0-0d03-4db4-b69b-f4bd39d9f641</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
