<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Assurance M</name>
   <tag></tag>
   <elementGuidId>7985285a-ddac-4b98-9443-0d93b4369f03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;user-listing&quot;]/div/div[1]/div[2]/kendo-dropdownlist</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b6d3166a-10a3-4253-8ddc-b1cbac315bb8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4ebe243d-6613-430f-a222-c9b4dd1336d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>0e3e117d-8389-45bb-89ae-4cc17e56c97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>be112060-d385-4f66-9eae-1dc658fc2bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b6d3166a-10a3-4253-8ddc-b1cbac315bb8</value>
      <webElementGuid>11e4a763-177a-4dda-91ce-4aa7ea9a5807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Assurance M</value>
      <webElementGuid>7850ca6b-de08-41c5-9a03-4f485478e211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b6d3166a-10a3-4253-8ddc-b1cbac315bb8&quot;)</value>
      <webElementGuid>475411c2-ae54-4cff-9f59-076130debe68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='b6d3166a-10a3-4253-8ddc-b1cbac315bb8']</value>
      <webElementGuid>c456870c-7bca-415b-a63e-41a8dc9f07ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-113fbc90-40f0-4e3d-8048-150d90094e1a']/span</value>
      <webElementGuid>561b1ecd-2981-42cb-8051-469d9045fa21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/following::span[2]</value>
      <webElementGuid>3f3e3717-0cab-4495-8d30-70c89b3b2de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PETRONAS Penapisan Terengganu Sdn Bhd'])[1]/following::span[4]</value>
      <webElementGuid>2fe425d9-4e73-4102-8372-db86d8f37395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[1]/preceding::span[3]</value>
      <webElementGuid>2672bbec-edeb-48ef-a5ff-396618fb6315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Template'])[1]/preceding::span[4]</value>
      <webElementGuid>74f3df34-b43a-44f4-9e6c-89b34ec7b57a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Assurance M']/parent::*</value>
      <webElementGuid>2c1c2d97-3584-412a-a9ac-33d6977fbed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/kendo-dropdownlist/span/span</value>
      <webElementGuid>01b08581-017b-45df-9e91-5c4b2af4cc3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'b6d3166a-10a3-4253-8ddc-b1cbac315bb8' and (text() = 'Assurance M' or . = 'Assurance M')]</value>
      <webElementGuid>05b6df29-7b8c-4157-9842-7abfed0c2f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='8e4c13d5-23ba-4e95-9ef5-0adeda5dbb9e']</value>
      <webElementGuid>ca807bac-ca16-466c-82ec-6db06a0f0b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-db4d932f-c964-499f-8d67-58e6d5cc42f6']/span</value>
      <webElementGuid>4c540be4-709c-4208-a3a3-cf18995393a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '8e4c13d5-23ba-4e95-9ef5-0adeda5dbb9e' and (text() = 'Assurance M' or . = 'Assurance M')]</value>
      <webElementGuid>14f745ca-fd6a-4638-820c-e928535b85a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
