<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Admin Homepage</name>
   <tag></tag>
   <elementGuidId>81e29d69-6b76-4cd8-8116-cc3d9b5b7301</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='7e9e07fe-9afa-4976-af82-ec9469d8010d']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#7e9e07fe-9afa-4976-af82-ec9469d8010d</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>64496330-169b-48c6-8de7-b7461db0067d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>94f7308e-71cf-4440-8561-59d325c99242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>864113c1-893e-4d29-9382-539cecf2ecf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>7e9e07fe-9afa-4976-af82-ec9469d8010d</value>
      <webElementGuid>7f2ecab3-10e8-4c85-b88f-f093bdf33e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin Homepage </value>
      <webElementGuid>7d77d0f2-d616-40c7-9be0-49510b84703d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;7e9e07fe-9afa-4976-af82-ec9469d8010d&quot;)</value>
      <webElementGuid>303fa583-6ae5-44f6-8b40-add8b6feae08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='7e9e07fe-9afa-4976-af82-ec9469d8010d']</value>
      <webElementGuid>d303fbb8-73af-4f17-a826-4d7b221d5fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-09a8c32d-a81d-46a5-9147-dfc3bda3d698']/span</value>
      <webElementGuid>4841c606-338b-415e-ab75-1e269ff03483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Notifications (0)'])[1]/preceding::span[3]</value>
      <webElementGuid>f34ccf69-ff1a-41ab-af91-1a8718a792cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>86997702-794a-4f29-893d-2530faa6a4a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '7e9e07fe-9afa-4976-af82-ec9469d8010d' and (text() = 'Admin Homepage ' or . = 'Admin Homepage ')]</value>
      <webElementGuid>d462ecd1-0ed1-476e-ac2d-81656645383c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
