<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__84ef8b56-3751-4740-8193-4d9e2703f9cd</name>
   <tag></tag>
   <elementGuidId>6946d157-373b-404e-87cd-9d0a4f2ff498</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='k-4a3c8e5b-1ed6-4f07-a4c5-9c964cd19fd7']//span[@class='k-select']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#84ef8b56-3751-4740-8193-4d9e2703f9cd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c959b13b-c29b-472d-a3b2-9070606c31fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>df81f9a4-d50a-4722-aa95-b59d011bacef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>f03a7256-c0c4-4fcb-96c5-0408f58485c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>84ef8b56-3751-4740-8193-4d9e2703f9cd</value>
      <webElementGuid>fe9f91d3-b479-449d-8eba-75e566c4fb4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;84ef8b56-3751-4740-8193-4d9e2703f9cd&quot;)</value>
      <webElementGuid>cf276687-cfa5-47ee-8f9b-982d241b41e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='84ef8b56-3751-4740-8193-4d9e2703f9cd']</value>
      <webElementGuid>871e2760-8ece-4f42-97d5-6a14b9414b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-48009821-0bb1-4942-b991-18651420cea1']/span</value>
      <webElementGuid>0d3f35ac-cd10-400e-883d-85bb616d078b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::span[2]</value>
      <webElementGuid>43623525-ca1c-43ca-a9c4-dced71f8e64c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/preceding::span[3]</value>
      <webElementGuid>cb874511-0575-4786-83cd-633b814081a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-work-information/div/div/div/div[2]/div/div[2]/kendo-dropdownlist/span/span</value>
      <webElementGuid>307a03ef-9cb8-4a0e-a49f-da64f858d765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '84ef8b56-3751-4740-8193-4d9e2703f9cd']</value>
      <webElementGuid>eed4eddc-cc5d-4597-9ea9-d328cfc7aefa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
