<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__Location</name>
   <tag></tag>
   <elementGuidId>5290c5e1-90a6-4f65-94d5-e36652ddcf6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='work-location']//kendo-dropdownlist</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#2c795fde-3181-45a3-a04f-c0aa1245c98a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3d383282-ea5d-4176-ad9f-c38839b9ca16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>d0b1c7e2-19cf-4398-bce8-da1864655fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>a54a54d4-c16c-486c-bfae-6519179871bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>2c795fde-3181-45a3-a04f-c0aa1245c98a</value>
      <webElementGuid>35872e7f-7e79-47a9-8f47-5efb94ffddd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2c795fde-3181-45a3-a04f-c0aa1245c98a&quot;)</value>
      <webElementGuid>4639728a-d247-4488-a1f6-8573ac4db927</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='2c795fde-3181-45a3-a04f-c0aa1245c98a']</value>
      <webElementGuid>8b81afc9-5334-41b6-b674-42036217ef78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-2edd8a3b-f4f7-4d69-a424-0fdfe628461c']/span</value>
      <webElementGuid>0d68bb9e-fc56-45a5-bdb9-8b7e883f929c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::span[2]</value>
      <webElementGuid>8c1c2ad7-21d3-42df-8a25-72ad346b354f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::span[3]</value>
      <webElementGuid>3e87828f-3d3c-48b3-9d84-a1166e372e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/kendo-dropdownlist/span/span</value>
      <webElementGuid>34887196-c8a7-4c5c-81ca-444c6f3bb392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '2c795fde-3181-45a3-a04f-c0aa1245c98a']</value>
      <webElementGuid>92fd6255-6069-4242-bcf4-ffa5f2b2194b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
