<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select role</name>
   <tag></tag>
   <elementGuidId>8208d9d2-5e63-44e3-a8b2-94ccc4d5ddc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='acfe6375-7545-4aab-b729-dea1835e9b80']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acfe6375-7545-4aab-b729-dea1835e9b80</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f97293e5-13fa-419c-8d2f-ae06bf0ba847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>d7d68969-dabb-4a4b-84d6-3ae863b88cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>19ca681e-4d12-46fb-b997-74fde17c3b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acfe6375-7545-4aab-b729-dea1835e9b80</value>
      <webElementGuid>56b75d5b-dfc8-4c7e-91ca-2e655a193cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select role</value>
      <webElementGuid>f9678dda-944a-476e-986b-17b011ce6eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acfe6375-7545-4aab-b729-dea1835e9b80&quot;)</value>
      <webElementGuid>c33d67fc-d247-43ba-8fc9-1729d8023dfe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='acfe6375-7545-4aab-b729-dea1835e9b80']</value>
      <webElementGuid>c6f6e5b0-63fb-4739-af72-701b145b8134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-9ded028a-4c47-447f-abc5-59eeae05a520']/span</value>
      <webElementGuid>4b8a7a16-28e2-48f4-8cb8-e2e357c10e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::span[2]</value>
      <webElementGuid>e5dcbf63-5819-4a02-a780-3245b21b98a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location Details'])[1]/preceding::span[3]</value>
      <webElementGuid>34cc94af-e5e6-448b-87ed-0907c748d2a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Location, yet.'])[1]/preceding::span[3]</value>
      <webElementGuid>29384b21-17df-4fea-bc38-6389b40ef703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select role']/parent::*</value>
      <webElementGuid>12501378-bef3-4d3b-a7e5-60f89f70779e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/kendo-dropdownlist/span/span</value>
      <webElementGuid>dd62a446-56ab-4183-8226-2e4557620f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'acfe6375-7545-4aab-b729-dea1835e9b80' and (text() = 'Select role' or . = 'Select role')]</value>
      <webElementGuid>0d3aab82-5352-4b0f-b45f-1018f329288e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
