<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Demo</name>
   <tag></tag>
   <elementGuidId>777a9688-1b82-477a-a9a9-78dfbedce0c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;user-listing&quot;]/div/div[1]/div[1]/kendo-dropdownlist</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#8c5de3b4-876b-40eb-8b11-370912d33b39</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dc1d2bab-8ce1-45e4-a91c-337aba299e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>30a0ec07-c62b-4531-9447-8e29317c64a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>05f4b067-ae58-4fb6-86bf-3f231d294965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>8c5de3b4-876b-40eb-8b11-370912d33b39</value>
      <webElementGuid>3ec09cec-253c-4109-a3ff-cdd1369626b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Demo</value>
      <webElementGuid>185b0f3f-1f62-47c3-887c-64ba58074c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;8c5de3b4-876b-40eb-8b11-370912d33b39&quot;)</value>
      <webElementGuid>7c785e49-4478-409c-a44f-97291aa355c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='8c5de3b4-876b-40eb-8b11-370912d33b39']</value>
      <webElementGuid>e97ee938-ff85-48b0-9ebb-71c155feb618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-4d076aa9-52c3-4fb6-907a-0badfff9a06d']/span</value>
      <webElementGuid>bb031e1f-81c7-4b4a-9382-279db323a478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPU'])[1]/following::span[2]</value>
      <webElementGuid>aaa9985e-72a5-47f2-a90b-c228bf271282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role Management'])[3]/following::span[2]</value>
      <webElementGuid>4c8d6585-e2c9-458b-9d66-c349981c369a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/preceding::span[3]</value>
      <webElementGuid>ff99518a-03fa-423e-ba79-c2e4fefcbb64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Testing'])[1]/preceding::span[3]</value>
      <webElementGuid>f002aa22-59eb-4a32-bae7-682685c16f38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Demo']/parent::*</value>
      <webElementGuid>e88e72e0-1586-4822-8e68-54d1dab2f39b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/kendo-dropdownlist/span/span</value>
      <webElementGuid>f9c6fbcb-e965-486b-b31b-cc2d020f4b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '8c5de3b4-876b-40eb-8b11-370912d33b39' and (text() = 'Demo' or . = 'Demo')]</value>
      <webElementGuid>17cc742d-5cb8-46cd-aa77-55342cfdfb96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='125e4732-80b0-42d0-a4ab-b8f700675026']</value>
      <webElementGuid>50676f2b-ec3f-4fc3-a282-54b70cbea884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-0e0a5a4f-2d01-4092-b369-0abd06f84019']/span</value>
      <webElementGuid>e859d3e7-f748-4050-ab7a-0c76002bb518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '125e4732-80b0-42d0-a4ab-b8f700675026' and (text() = 'Demo' or . = 'Demo')]</value>
      <webElementGuid>d61a7117-da12-4b33-ba6e-db75b4485728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='451506ce-91a1-43f7-8ebb-eaec876ce038']</value>
      <webElementGuid>92d68471-efa6-4db3-a85b-83fa79bb889e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-896e4ffe-aee8-4a60-8800-d61d48c0ae3b']/span</value>
      <webElementGuid>dac6e3b1-50a1-4e73-8486-4cd76149fee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::span[2]</value>
      <webElementGuid>7af31e34-6486-4d4b-9967-04cbfdb22181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPU'])[1]/following::span[3]</value>
      <webElementGuid>5dc20d31-ea48-41dd-a562-31387120843f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::span[3]</value>
      <webElementGuid>9f8110fe-f0e6-44f9-8c93-e795866f4e03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '451506ce-91a1-43f7-8ebb-eaec876ce038' and (text() = 'Demo' or . = 'Demo')]</value>
      <webElementGuid>409628b7-f850-4ea8-8dc3-191855baaf57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
