<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_EWR</name>
   <tag></tag>
   <elementGuidId>01e9b2c8-1c35-47c1-80ae-e25e7ba08211</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span[title=&quot;EWR&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Announcement'])[1]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d730636a-bfa1-4525-b3a8-8c81b201fa54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>EWR</value>
      <webElementGuid>e51964ab-811c-418e-a2fc-69d3a92cb3d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EWR </value>
      <webElementGuid>5e5f0ef2-2ceb-421a-9617-c346645e23d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-tns-0-1&quot;]/dialog-holder[1]/dialog-wrapper[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal fade show in&quot;]/app-detail-form[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/app-select-action-component[1]/div[@class=&quot;container-role&quot;]/div[1]/div[@class=&quot;body-bottom&quot;]/div[@class=&quot;multi-tabs&quot;]/div[@class=&quot;wrap-tabs&quot;]/div[@class=&quot;tab ng-star-inserted&quot;]/span[1]</value>
      <webElementGuid>7755a4c6-7d31-487e-80f6-dec8137d73f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Announcement'])[1]/following::span[1]</value>
      <webElementGuid>e285e4df-910e-4ea1-9d2d-8759be76d24d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Execution'])[1]/following::span[5]</value>
      <webElementGuid>1fd75cf0-b0fa-4d72-a883-67f8c2a427c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General'])[1]/preceding::span[1]</value>
      <webElementGuid>61780283-3460-4a93-bfc0-23bdf1329341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Handover and Handback'])[1]/preceding::span[2]</value>
      <webElementGuid>502313cd-6a4b-4aa7-a356-f5a18465190a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='EWR']/parent::*</value>
      <webElementGuid>706f36c3-f76b-4a0d-b93f-f2f5157cac56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-select-action-component/div/div/div/div/div/div[2]/span</value>
      <webElementGuid>bb8444f3-f495-4ad2-8378-f34018d8b599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'EWR' and (text() = 'EWR ' or . = 'EWR ')]</value>
      <webElementGuid>8b99a04b-f9da-453d-a906-ac2034bb7b6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
