<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_REG-EVENT-01-TA</name>
   <tag></tag>
   <elementGuidId>4e467a17-fd42-416b-a366-162b4697c4b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='67a4c750-a724-4aa9-8b69-8823ea10d45c']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#67a4c750-a724-4aa9-8b69-8823ea10d45c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8bc58a1e-9022-4fe2-888a-c03aa04fa442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>d9c72a53-921b-4d19-a41a-88d609a63499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>44879ad7-4bd1-43d7-bb98-58751e3cc32c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>67a4c750-a724-4aa9-8b69-8823ea10d45c</value>
      <webElementGuid>a947910f-3324-425a-acfe-d9dce72fd3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>REG-EVENT-01-TA</value>
      <webElementGuid>5acc1249-8840-42a9-8a3f-af5239f79abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;67a4c750-a724-4aa9-8b69-8823ea10d45c&quot;)</value>
      <webElementGuid>a4716b67-794d-43e1-863f-b95782e13201</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='67a4c750-a724-4aa9-8b69-8823ea10d45c']</value>
      <webElementGuid>622e6f1e-aad1-4ca4-9ea8-8595ba3ddd8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-4a903f50-51b0-4d6a-a13b-4fa331d172ad']/span</value>
      <webElementGuid>5b10c690-b0f3-4433-9ce4-bb669907642c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::span[2]</value>
      <webElementGuid>d9d4338a-9bd0-4d6c-a6c0-7e8b2d90e962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/following::span[3]</value>
      <webElementGuid>abad0399-e8b1-403e-9556-1e4c8d80f93c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register Multiple User'])[1]/preceding::span[3]</value>
      <webElementGuid>0407ec27-3dcd-4023-b882-3694f5b31440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New User'])[1]/preceding::span[4]</value>
      <webElementGuid>2e50e7eb-9fe1-4584-aa17-1dca838978b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='REG-EVENT-01-TA']/parent::*</value>
      <webElementGuid>40cad376-b83d-4e45-8342-6c96f84486a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/kendo-dropdownlist/span/span</value>
      <webElementGuid>67c5c3a0-3760-4f87-9c0a-87fdcaffe56c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '67a4c750-a724-4aa9-8b69-8823ea10d45c' and (text() = 'REG-EVENT-01-TA' or . = 'REG-EVENT-01-TA')]</value>
      <webElementGuid>05eaf5b4-c61e-4372-9463-3ae39711687c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
