<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Assurance M_1</name>
   <tag></tag>
   <elementGuidId>390d66e1-b206-41c2-a5e4-8e90b07740ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='8346d46b-040a-4ba4-8e3c-173c6852ce00']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#8346d46b-040a-4ba4-8e3c-173c6852ce00</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a652b230-e613-465e-b329-16d5cacc5264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>d070d54d-8d13-41fa-bff1-233368d58830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>7edd7e74-7c8c-4dbf-ad05-b83a193fc5ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>8346d46b-040a-4ba4-8e3c-173c6852ce00</value>
      <webElementGuid>0ced3edb-3656-4851-b7a3-c4b876296114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Assurance M</value>
      <webElementGuid>34cd49e7-e0c8-47a1-9ce2-87938c26ba65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;8346d46b-040a-4ba4-8e3c-173c6852ce00&quot;)</value>
      <webElementGuid>e4f3d64f-95fe-4455-a75a-1baea7ef0919</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='8346d46b-040a-4ba4-8e3c-173c6852ce00']</value>
      <webElementGuid>0bb24427-8e1b-435a-9f64-ff0cf71dc90b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-1dde2e65-f0e3-464d-9333-fbf9cbcbf819']/span</value>
      <webElementGuid>c04967d9-572d-4cb5-8919-866d142ff3d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::span[2]</value>
      <webElementGuid>b57fb7a2-0b8e-47ef-a4b2-c9543c30e965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/following::span[3]</value>
      <webElementGuid>681f1926-8233-4085-a9ff-f769e8a37973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register Multiple User'])[1]/preceding::span[3]</value>
      <webElementGuid>928d2d18-6b0b-4827-b104-f379dfbde8ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New User'])[1]/preceding::span[4]</value>
      <webElementGuid>f5fa87ce-818d-4739-89ea-245f0d53c82d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Assurance M']/parent::*</value>
      <webElementGuid>c58bb836-558b-4f33-8abe-08133da29f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/kendo-dropdownlist/span/span</value>
      <webElementGuid>782088fd-63ee-4ae9-af08-48337dac042d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '8346d46b-040a-4ba4-8e3c-173c6852ce00' and (text() = 'Assurance M' or . = 'Assurance M')]</value>
      <webElementGuid>5363e345-8377-4634-9316-bc299a579f66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
