<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Click on User</name>
   <tag></tag>
   <elementGuidId>07740a54-c6b4-4ac5-ae94-006e7fc76262</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;user-listing&quot;]/div/div[2]/kendo-grid/div/kendo-grid-list/div/div[1]/table/tbody/tr[1]/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>37098463-4e68-4b76-bfb7-cb8c105c58e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>948ae469-8981-40bc-ac33-d257ac3070ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-touch-action-auto ng-star-inserted</value>
      <webElementGuid>3c8bcb56-89a6-43a7-9516-e4dde0e4020e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-kendo-grid-column-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>fab05acb-df0e-4c64-8504-fe2a4299652b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>dfd0ba9a-9d3a-4395-9e92-450896a78edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>167b2f56-5712-4098-9a83-c65cdeff1087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>subverify5@pethlab.com</value>
      <webElementGuid>6e6f654c-ad9e-46dd-b123-a75bf0bf5e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-listing&quot;)/div[1]/div[@class=&quot;container-body ng-star-inserted&quot;]/kendo-grid[@class=&quot;custom-grid k-widget k-grid&quot;]/div[@class=&quot;k-grid-aria-root&quot;]/kendo-grid-list[@class=&quot;k-grid-container ng-star-inserted&quot;]/div[@class=&quot;k-grid-content k-virtual-content&quot;]/div[@class=&quot;k-grid-table-wrap&quot;]/table[@class=&quot;k-grid-table&quot;]/tbody[1]/tr[@class=&quot;k-alt ng-star-inserted&quot;]/td[@class=&quot;k-touch-action-auto ng-star-inserted&quot;]</value>
      <webElementGuid>def333ee-8880-4054-8773-e32ba7895d2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='user-listing']/div/div[2]/kendo-grid/div/kendo-grid-list/div/div/table/tbody/tr[4]/td[3]</value>
      <webElementGuid>4f3c7036-7698-401f-8fa8-c052a05e5807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Faizal, Osman'])[1]/following::td[1]</value>
      <webElementGuid>eb8589bc-376e-4017-8d1a-e75c66d39a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtask Verifier'])[1]/following::td[5]</value>
      <webElementGuid>925ba573-5d75-45c2-9510-b9bb1f847c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtask Verifier 3'])[1]/preceding::td[1]</value>
      <webElementGuid>a2121ea7-0bb7-4ef4-bc42-52d7b049a51d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='items per page'])[1]/preceding::td[4]</value>
      <webElementGuid>1b201cc6-8fe7-453e-b436-a1484b60b487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='subverify5@pethlab.com']/parent::*</value>
      <webElementGuid>85dbb6de-4be0-455c-a353-7782f3fd6711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[3]</value>
      <webElementGuid>0dbeafa7-c484-40ee-94ac-37f6ca9d9876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'subverify5@pethlab.com' or . = 'subverify5@pethlab.com')]</value>
      <webElementGuid>7577492e-e9b0-4cf0-b4d4-a7e28cdb8805</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
