<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Role on User</name>
   <tag></tag>
   <elementGuidId>6c6a1904-589f-4f74-a7be-92e72d3b2e5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='k-tabstrip-tabpanel-1']/kendo-grid/div/kendo-grid-list/div/div/table/tbody/tr/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>4a3d661b-62b3-4aaf-aec2-98b2dca844fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>12cacffa-ff48-4a82-a358-394824b93e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-touch-action-auto ng-star-inserted</value>
      <webElementGuid>75a0d3b5-639f-45c9-9d45-42b53bd3e406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-kendo-grid-column-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a3a77930-c95c-4c88-a30e-ea2ce439dc83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>daf0afbe-2e00-4045-82bd-2ade1a8d3719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>182dd0bd-548f-4665-9fc8-88e0c15d46ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subtask Verifier 3</value>
      <webElementGuid>eaeb3019-670d-4190-bf0d-58ea3e173b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-tabstrip-tabpanel-1&quot;)/kendo-grid[@class=&quot;custom-grid k-widget k-grid ng-star-inserted&quot;]/div[@class=&quot;k-grid-aria-root&quot;]/kendo-grid-list[@class=&quot;k-grid-container ng-star-inserted&quot;]/div[@class=&quot;k-grid-content k-virtual-content&quot;]/div[@class=&quot;k-grid-table-wrap&quot;]/table[@class=&quot;k-grid-table&quot;]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;k-touch-action-auto ng-star-inserted&quot;]</value>
      <webElementGuid>fd5233ea-8bb9-4e25-83f3-66ab3c3f90dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='k-tabstrip-tabpanel-1']/kendo-grid/div/kendo-grid-list/div/div/table/tbody/tr/td[2]</value>
      <webElementGuid>9808e423-cb22-4531-81a4-8018904b71c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOCATION'])[1]/following::td[2]</value>
      <webElementGuid>b934d717-ffd2-434c-a9ed-b434e5f069c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ROLE NAME'])[1]/following::td[2]</value>
      <webElementGuid>d15a78db-c24b-4602-acad-8c9ef82d3da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CDU'])[1]/preceding::td[1]</value>
      <webElementGuid>0a2aaeff-a843-4940-ad83-09eaa4bab469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CDU'])[2]/preceding::td[1]</value>
      <webElementGuid>c6a4c5e8-d676-407d-883a-d6ffb0a105ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Subtask Verifier 3']/parent::*</value>
      <webElementGuid>74f869df-5679-4a16-97d6-b3f6dad2c136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>fd356d2f-b28f-455d-8ab0-0291419220c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Subtask Verifier 3' or . = 'Subtask Verifier 3')]</value>
      <webElementGuid>3c23dc55-3628-42f3-a523-22210afb21fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
