<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Work Detailing Justification Impact Of _559bb3</name>
   <tag></tag>
   <elementGuidId>5622ad89-f421-4d58-8730-890b1cfc511e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#work-detailing</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='work-detailing']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8691f4e5-dbdb-4b52-8491-be4507344b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>work-detailing</value>
      <webElementGuid>4b911e75-65c1-4eea-a352-1727b86cacd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card</value>
      <webElementGuid>30344220-ed6e-4599-bd19-aab6c1dcb305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Work Detailing Justification *Impact Of Not Executing EWR *Risk Assessment Result *Mitigation / Action * Require Technical Review Please confirm Technical Review is required prior to submissionONOFFAssign To  Please select a reviewer  Barua, Debraj  Bin Abdullah, M Syafiq  Kumar, John  Ghagre, Sachin  Updater1, Training Propose to transfer / register the deleted worklist? *In routine maintenanceIn next opportunityDelete the worklist</value>
      <webElementGuid>9d634495-f92b-4861-9f9e-061b4eeac2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;work-detailing&quot;)</value>
      <webElementGuid>d918ba76-a17a-4c32-ab4e-06b13d93b21f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='work-detailing']</value>
      <webElementGuid>0f53da03-b343-4665-9a3e-caf45a663a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::div[1]</value>
      <webElementGuid>770ddfcc-9ef0-4bf6-a1f8-dc298e72f61a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-create-request/div/div/div/div/div[3]</value>
      <webElementGuid>c88f73ba-b9c3-4d45-ab5a-d5e4d897c5d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'work-detailing' and (text() = ' Work Detailing Justification *Impact Of Not Executing EWR *Risk Assessment Result *Mitigation / Action * Require Technical Review Please confirm Technical Review is required prior to submissionONOFFAssign To  Please select a reviewer  Barua, Debraj  Bin Abdullah, M Syafiq  Kumar, John  Ghagre, Sachin  Updater1, Training Propose to transfer / register the deleted worklist? *In routine maintenanceIn next opportunityDelete the worklist' or . = ' Work Detailing Justification *Impact Of Not Executing EWR *Risk Assessment Result *Mitigation / Action * Require Technical Review Please confirm Technical Review is required prior to submissionONOFFAssign To  Please select a reviewer  Barua, Debraj  Bin Abdullah, M Syafiq  Kumar, John  Ghagre, Sachin  Updater1, Training Propose to transfer / register the deleted worklist? *In routine maintenanceIn next opportunityDelete the worklist')]</value>
      <webElementGuid>13f9a299-3334-4937-ada7-677c8d5b6b29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
