<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ONOFF</name>
   <tag></tag>
   <elementGuidId>da06d1e4-6ace-4b61-be7c-4e673bcd4049</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;work-detailing&quot;]//kendo-switch</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#k-b6e9a23e-dff1-4e0d-86ab-75ac9ff71755</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7135ae89-7462-4d0e-9437-c9cddd9a16ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>b52c74c3-c49e-46c9-8e05-83f332cd79c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-switch-container</value>
      <webElementGuid>a358c29d-489b-4794-ac4e-cbd6ead35022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>k-b6e9a23e-dff1-4e0d-86ab-75ac9ff71755</value>
      <webElementGuid>7afff5d2-8bd3-4443-9993-875974527452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9576f4a9-678d-4f14-9a3e-c296ccb05340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2f134e6a-8530-4325-9573-1b411361a0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ONOFF</value>
      <webElementGuid>ef73ec25-9e04-4e3d-b98d-2e6e3799a772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-b6e9a23e-dff1-4e0d-86ab-75ac9ff71755&quot;)</value>
      <webElementGuid>48a070c4-53c5-4b03-af84-081983c09fa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='k-b6e9a23e-dff1-4e0d-86ab-75ac9ff71755']</value>
      <webElementGuid>40335c5b-1608-407a-bac9-82658f1ba9d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='work-detailing']/app-work-detailing/div/div/div[2]/div/div[2]/div/kendo-switch/span</value>
      <webElementGuid>72832b31-ee3f-47ee-aa8d-a412db0571e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please confirm Technical Review is required prior to submission'])[1]/following::span[1]</value>
      <webElementGuid>b4f87b59-f1c8-4db1-aa98-849ccb5a23fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Require Technical Review'])[1]/following::span[1]</value>
      <webElementGuid>ddd34dc6-daad-4244-b9ce-102b5d52b872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/preceding::span[4]</value>
      <webElementGuid>7a97dcf2-1cf7-4247-a958-d8e9bb2122b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kendo-switch/span</value>
      <webElementGuid>98b73586-17a9-4ffe-bc24-15eb5e142327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'k-b6e9a23e-dff1-4e0d-86ab-75ac9ff71755' and (text() = 'ONOFF' or . = 'ONOFF')]</value>
      <webElementGuid>4cc4bd34-5d6e-42f2-b01b-aa4cfc24e9d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
