<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__Justification</name>
   <tag></tag>
   <elementGuidId>72026bed-d4d8-4405-8976-699ccbc86b21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;work-detailing&quot;]//textarea[contains(@formcontrolname, 'justification')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.form-control.custom-input.ng-untouched.ng-dirty.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>353fb979-9015-44ba-8bb2-5addc4753978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add Description</value>
      <webElementGuid>b6c4d24e-79c1-449c-b80f-39d59d721f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8b999bea-34d9-4e8c-800e-9dd0175a4b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>06e42a21-b340-4545-802d-b1d32e3afb9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom-input ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>bb1049fa-cb09-4860-8cfd-7d3580012fc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;work-detailing&quot;)/app-work-detailing[1]/div[@class=&quot;bootstrap-wrapper ng-untouched ng-invalid ng-dirty&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 col-lg-12&quot;]/div[@class=&quot;row kd-custom&quot;]/div[@class=&quot;col-md-12 custom-magrin-bottom ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/textarea[@class=&quot;form-control custom-input ng-untouched ng-dirty ng-valid&quot;]</value>
      <webElementGuid>9758b704-f558-41b7-88d0-ac7a8215bb6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@type='text'])[2]</value>
      <webElementGuid>dd05a0f6-e25b-4853-933e-f6c2df7f1b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='work-detailing']/app-work-detailing/div/div/div/div[2]/div/div/div/textarea</value>
      <webElementGuid>7eb3b05a-d8ad-4cb9-a7af-4d5cd91605f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-work-detailing/div/div/div/div[2]/div/div/div/textarea</value>
      <webElementGuid>9fe14dfd-249d-4b9e-a86e-3769446391c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Add Description' and @type = 'text']</value>
      <webElementGuid>5e7cf3d6-2b26-4ce6-b5d8-3cd9b0e08c9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
