<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__Mitigation</name>
   <tag></tag>
   <elementGuidId>705deb03-25d5-45f7-bc9c-1dc64cc712e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;work-detailing&quot;]//textarea[contains(@formcontrolname, 'mitigationResult')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.form-control.custom-input.ng-untouched.ng-dirty.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d1c7fa76-e100-4fba-b1ab-91bb67444d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add Description</value>
      <webElementGuid>7c5b1a4c-f0b7-4567-a7ca-06561e34ec2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a842b551-e959-4a76-bbbd-ecd4d906eafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>6ab7226e-c970-4094-bbe3-240841908321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom-input ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>8a7d1505-ff85-4488-9af4-c4b0ab3ca010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;work-detailing&quot;)/app-work-detailing[1]/div[@class=&quot;bootstrap-wrapper ng-untouched ng-invalid ng-dirty&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 col-lg-12&quot;]/div[@class=&quot;row kd-custom&quot;]/div[@class=&quot;col-md-12 custom-magrin-bottom ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/textarea[@class=&quot;form-control custom-input ng-untouched ng-dirty ng-valid&quot;]</value>
      <webElementGuid>7ea29e70-fd52-455d-b0a5-10202e573c82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@type='text'])[2]</value>
      <webElementGuid>564efae5-bc1b-402b-8e6b-84813f6014f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='work-detailing']/app-work-detailing/div/div/div/div[2]/div/div/div/textarea</value>
      <webElementGuid>7b8b7ae5-d5fb-49fd-9ee3-1e7eef8cca4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-work-detailing/div/div/div/div[2]/div/div/div/textarea</value>
      <webElementGuid>fe8cbcf4-552b-4d74-961f-4fa0415a92f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Add Description' and @type = 'text']</value>
      <webElementGuid>faa6057e-7f14-4234-a94f-e6ec98169a7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
