<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__form-control custom-input textbox_7cb806</name>
   <tag></tag>
   <elementGuidId>c0ba7e28-ad84-4883-95a0-6e71ee6fed5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@class='form-control custom-input textboxDetail ng-dirty ng-valid ng-touched']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.form-control.custom-input.textboxDetail.ng-untouched.ng-dirty.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1b93f908-d206-45b7-9fc1-37700d30dee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write the comment...</value>
      <webElementGuid>c386ef3b-9ce5-4bb2-8b9d-a636f798a068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f7b7023-a3a6-41d8-a173-64339509ce58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>resourcesDetailing</value>
      <webElementGuid>62455d91-4b8b-4ba7-93af-d11a65a96c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom-input textboxDetail ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>8c749447-6dc0-47c9-8c03-bddf41ba451e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;work-information&quot;)/app-work-information[1]/div[@class=&quot;bootstrap-wrapper ng-star-inserted ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 col-lg-12&quot;]/div[@class=&quot;row kd-custom&quot;]/div[@class=&quot;col-md-12 ng-star-inserted&quot;]/div[@class=&quot;col-md-8&quot;]/textarea[@class=&quot;form-control custom-input textboxDetail ng-untouched ng-dirty ng-valid&quot;]</value>
      <webElementGuid>9788cb60-8586-429a-aaea-00fcd56e696a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@type='text']</value>
      <webElementGuid>f1702393-dcae-4cdf-b723-a961bc53967c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='work-information']/app-work-information/div/div/div/div[2]/div/div[3]/div[3]/textarea</value>
      <webElementGuid>213a3f85-ecef-4711-81ff-895127d8d3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::textarea[1]</value>
      <webElementGuid>79445f85-7eeb-4c1f-b550-e0a8bf0f0502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Detailing'])[1]/preceding::textarea[1]</value>
      <webElementGuid>baf98f56-3f20-4eda-9e44-209861f8ab58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>35884676-eb34-45b2-b388-09b7e905fa26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Write the comment...' and @type = 'text']</value>
      <webElementGuid>6e6cd144-ef2b-4f6b-9f8d-2ba7a8f2d6b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
