<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__Justification</name>
   <tag></tag>
   <elementGuidId>72026bed-d4d8-4405-8976-699ccbc86b21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@formcontrolname='justification']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.form-control.custom-input.ng-untouched.ng-dirty.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>eced1078-22f7-440e-bdee-838e1a64eca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add Description</value>
      <webElementGuid>8ee5271c-3e07-43a3-af42-8a5a11ba5cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>28f46cd7-9e0a-4283-80c2-5bd33bb612f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>37100b63-9999-445a-ac1f-874a58f4637d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom-input ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>95c1618d-12d8-45e8-b79c-374a5d0943dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;work-detailing&quot;)/app-work-detailing[1]/div[@class=&quot;bootstrap-wrapper ng-untouched ng-invalid ng-dirty&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 col-lg-12&quot;]/div[@class=&quot;row kd-custom&quot;]/div[@class=&quot;col-md-12 custom-magrin-bottom ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/textarea[@class=&quot;form-control custom-input ng-untouched ng-dirty ng-valid&quot;]</value>
      <webElementGuid>c6f5c6ff-843d-4d6e-94f7-f6ee3953dcff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@type='text'])[2]</value>
      <webElementGuid>b4c890a1-e195-4cce-843e-7e60d03b8f17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='work-detailing']/app-work-detailing/div/div/div/div[2]/div/div/div/textarea</value>
      <webElementGuid>cc9ee495-a9c2-490a-9e95-a1f37143066c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-work-detailing/div/div/div/div[2]/div/div/div/textarea</value>
      <webElementGuid>3aa5ba8e-0ea9-4816-98c0-ef06651adcd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Add Description' and @type = 'text']</value>
      <webElementGuid>446dd99a-e195-4e28-89f4-b4414af84afe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
