<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox dalam</name>
   <tag></tag>
   <elementGuidId>acee714f-94bc-4f23-a7d3-2bfa3bfe1228</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#k-grid1-checkbox0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id, 'k-grid1-checkbox')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d1fe90e-0d18-4180-9e92-8fef65acaaec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-checkbox</value>
      <webElementGuid>d3aec574-0997-48e8-a9d7-6727410e9797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>k-grid1-checkbox0</value>
      <webElementGuid>93cf04e0-b3a6-4656-b16b-d7f2c2f6a9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select Row</value>
      <webElementGuid>690b54fc-1617-4523-91e7-f0191c706dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1c8184af-8645-46b7-973d-7f70f49ebcd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-grid1-checkbox0&quot;)</value>
      <webElementGuid>7b515a12-2836-4026-959f-0782265ab182</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='k-grid1-checkbox0']</value>
      <webElementGuid>bc5f35dc-8683-4505-8f48-75c86128d82c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>045392b7-ed6f-42c8-8a10-2a4bd023c979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'k-grid1-checkbox0' and @type = 'checkbox']</value>
      <webElementGuid>1e51e3b7-967c-48a2-ba9c-8ac0bf3e13af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
