<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__k-37fa3964-94ac-41d3-a928-1926d07bb6d4</name>
   <tag></tag>
   <elementGuidId>4659ae75-c365-4b3b-8cee-2b0f357b2ebd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#k-37fa3964-94ac-41d3-a928-1926d07bb6d4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='k-37fa3964-94ac-41d3-a928-1926d07bb6d4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Tag No&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c8e8a2d-5d51-4f15-bdb3-45dfcdcd2d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>c999c492-1108-440e-9266-eb2872361e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>k-37fa3964-94ac-41d3-a928-1926d07bb6d4</value>
      <webElementGuid>657f0f87-54cc-4451-9196-186ffbf3fc02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>35e6b92e-95c0-4f80-a6e5-b1d0b9840abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tag No</value>
      <webElementGuid>c442f095-6250-43fd-bee1-fb587541d30f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-37fa3964-94ac-41d3-a928-1926d07bb6d4&quot;)</value>
      <webElementGuid>d4449fbd-cdc2-469c-aa96-6e4c883e8fc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='k-37fa3964-94ac-41d3-a928-1926d07bb6d4']</value>
      <webElementGuid>5d0e1a22-9c29-4e34-93fd-929725a71f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='work-information']/app-work-information/div/div/div/div[2]/div/div[4]/kendo-textbox/input</value>
      <webElementGuid>4cf784d1-fab8-4fee-80fe-bac6eae791af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a816de37-ac8f-4449-8159-b0573d1b843e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'k-37fa3964-94ac-41d3-a928-1926d07bb6d4' and @placeholder = 'Tag No']</value>
      <webElementGuid>fa995aa8-d03b-44db-ad69-dc199fd5df22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
