<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox</name>
   <tag></tag>
   <elementGuidId>a96559e8-a53b-4c6b-8376-d07c8be16bef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;work-detailing&quot;]/app-work-detailing/div/div/div[1]/div[2]/div
&#xd;
</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;work-detailing&quot;]/app-work-detailing/div/div/div[1]/div[2]/div&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;work-detailing&quot;]/app-work-detailing/div/div/div[1]/div[2]/div
&#xd;
</value>
      <webElementGuid>b360a1c1-7207-4b69-8f70-47d98ae43582</webElementGuid>
   </webElementProperties>
</WebElementEntity>
