<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DeleteTasklist</name>
   <tag></tag>
   <elementGuidId>c3cd611f-e228-4932-b2cf-2a5dff362b9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#k-grid1-checkbox0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Delete the tasklist']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0939ca88-a5a7-43bb-92f1-6ac048b32179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-checkbox</value>
      <webElementGuid>ac1dead2-80c0-47ee-a8ec-a9656f04af4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>k-grid1-checkbox0</value>
      <webElementGuid>40cbb20a-0a6e-4701-8591-0565ba55f6dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select Row</value>
      <webElementGuid>5262b84f-ab0f-4332-850a-7dd79dc3fa4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ba5096bd-6d20-4616-ac3c-57fe072f55e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-grid1-checkbox0&quot;)</value>
      <webElementGuid>148acbbe-518c-4665-bb4a-0397d1177112</webElementGuid>
   </webElementProperties>
</WebElementEntity>
