<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__k-2084d347-928a-4060-9475-070ad55b262f</name>
   <tag></tag>
   <elementGuidId>a7489b33-c660-4e94-af79-f5a02c08caee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#k-2084d347-928a-4060-9475-070ad55b262f</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='k-2084d347-928a-4060-9475-070ad55b262f']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Tag No&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b943abf-ab96-4e10-a3aa-384e9cdef34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>f3b04bae-535c-48b2-aa29-b9882f294845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>k-2084d347-928a-4060-9475-070ad55b262f</value>
      <webElementGuid>65ee3a5b-6fc8-42fd-aede-35df51787419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d1cbf5ca-8d3b-4a60-b243-2a8c6c494412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tag No</value>
      <webElementGuid>8856999e-7c6d-44dc-8b36-7b110da8b152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-2084d347-928a-4060-9475-070ad55b262f&quot;)</value>
      <webElementGuid>71db1639-0855-4f87-ab65-8cd4a8769350</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='k-2084d347-928a-4060-9475-070ad55b262f']</value>
      <webElementGuid>f82777e9-b6f6-48ae-b0a6-727234b94bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='work-information']/app-work-information/div/div/div/div[2]/div/div[4]/kendo-textbox/input</value>
      <webElementGuid>a907a5e2-0955-4ad9-bdc8-c60f5ee21c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>49d486f6-1a70-4af5-9287-2a737b15eeab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'k-2084d347-928a-4060-9475-070ad55b262f' and @placeholder = 'Tag No']</value>
      <webElementGuid>1bf04bba-9c3d-4ea4-b180-5fbcc79b221a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
