<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Job Description_k-grid1-checkbox0</name>
   <tag></tag>
   <elementGuidId>2f16b375-666e-49af-acd9-91958fd0d37a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#k-grid1-checkbox0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='k-grid1-checkbox0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Select Row TEST - SC5 - 02 Static TEST - SC5 - 02&quot;i] >> internal:label=&quot;Select Row&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f99776dc-670c-4694-b843-ce9769588e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-checkbox</value>
      <webElementGuid>66b1e57d-d4e5-4240-a159-dfa94026a491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>k-grid1-checkbox0</value>
      <webElementGuid>b89dbe22-6a94-4d1b-ae21-fa02b51679e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select Row</value>
      <webElementGuid>327fe614-7174-4d5a-8c49-9d2038350766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>370bf765-13bf-4646-b623-6ddb319d5724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-grid1-checkbox0&quot;)</value>
      <webElementGuid>317c5d42-dc37-4951-b809-03a406f7144a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='k-grid1-checkbox0']</value>
      <webElementGuid>aee41bb8-cf43-4339-bb5e-442fc0db95ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>7e035e0e-f65c-409d-af4e-87b235ebb50f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'k-grid1-checkbox0' and @type = 'checkbox']</value>
      <webElementGuid>6c21fc18-2548-414c-bc8e-777e0dffef59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
